import type { FrameworkDetailSpec } from '../components/FrameworkDetailPage';

export const frameworkDetails: Record<string, FrameworkDetailSpec> = {
  'field-state': {
    slug: 'field-state',
    title: 'Field State',
    kicker: 'State / GPI 1-3',
    meta: 'clear signal / close decisions / low drag',
    description: 'Field State businesses can see what is happening, make decisions close to the work, and update before the moment passes.',
    summary: [
      'Field State does not mean everyone is running loose. It means people have enough shared context to move without asking permission for every small step.',
      'This works when the world is changing and waiting costs more than trying something controlled, learning from it, and adjusting.',
    ],
    thesis: 'In Field State, the business has a clean enough memory and a short enough decision path that useful signals can turn into action before they go stale.',
    scale: [
      ['Score 1-3', 'Decisions happen near the work. Mistakes surface early. Knowledge is findable. Roles can bend around the problem.'],
      ['Score 4-6', 'Some parts still move cleanly, but the business is starting to add approvals, roles, tools, or habits that make movement less natural.'],
      ['Score 7-10', 'The field has collapsed into weight. Decisions travel farther, knowledge gets trapped, and the system spends more energy protecting its current shape.'],
      ['Watch for', 'Speed can turn into noise if nobody owns the lesson, the boundary, or the stop point.'],
    ],
    signals: [
      'A useful idea can be tested in days, not quarters.',
      'New people can find answers without asking the same veterans.',
      'Mistakes create updates to the system, not only blame or meetings.',
      'Teams can change a workflow without waiting for a full reorg.',
      'Top performers stay because the work has agency and signal.',
      'AI and automation remove routine drag instead of adding another approval layer.',
    ],
    examples: [
      ['Stripe', 'API-first operating logic. Authority and documentation support fast changes without turning every decision into a committee.'],
      ['GitLab', 'Handbook-first culture makes distributed knowledge part of the operating system.'],
      ['Shopify', 'Modular product and merchant feedback loops allow faster pivots than traditional retail systems.'],
      ['Nvidia', 'Founder-led context, ecosystem feedback, and architectural cadence keep learning loops tight even at scale.'],
    ],
    clientUse: [
      ['Map the flow', 'Show where the signal enters, who can act, and where the decision path stays clean.'],
      ['Protect movement', 'Find where new process, compliance, or growth could accidentally turn useful speed into drag.'],
      ['Set edges', 'Use simple rules so fast movement still has a boundary and a way to learn.'],
    ],
    next: ['Next: Transition State', '/gpi-framework/transition-state'],
  },
  'transition-state': {
    slug: 'transition-state',
    title: 'Transition State',
    kicker: 'State / GPI 4-6',
    meta: 'mixed signals / old habits / new pressure',
    description: 'Transition State businesses are caught between what used to work and what the current reality is starting to require.',
    summary: [
      'Transition State is where the business can still go either way. Some parts are learning and moving. Other parts are protecting old habits, old tools, and old promises.',
      'This is often the best time to intervene because the pattern has not hardened yet. The question is whether the business is opening up or closing down.',
    ],
    thesis: 'Transition State is not the middle. It is the fork. The business is either updating what it learned or building a new shell around old lessons.',
    scale: [
      ['Score 1-3', 'The business still behaves like a field. Signals move quickly, people can act near the work, and learning updates the system.'],
      ['Score 4-6', 'Some teams can decide and learn quickly. Others are still trapped in old approvals, tools, assets, or incentives.'],
      ['Score 7-10', 'The transition is hardening into particle behavior. The old model keeps winning even when the business says it wants to change.'],
      ['Watch for', 'The business can confuse activity with change and let temporary workarounds become the next permanent mess.'],
    ],
    signals: [
      'Leadership says transformation, but core incentives still reward the old operating model.',
      'Strong teams build local fixes that do not travel across the company.',
      'The company can move fast in crisis but slow down again afterward.',
      'Data exists, but decision rights are unclear.',
      'AI pilots, new tools, or dashboards appear before the operating questions are settled.',
      'Talent is split between builders who want movement and protectors who want stability.',
    ],
    examples: [
      ['Ford', 'EV transition while still carrying combustion assets, dealer networks, plants, and legacy economics.'],
      ['Disney', 'Streaming, parks, IP, ESPN, and legacy media economics pulling the operating system in different directions.'],
      ['Roblox', 'High knowledge velocity in product and creator loops, but capital intensity and profitability pressure complicate the path.'],
      ['Rivian', 'Software ambition moving through factories, supplier dependencies, and capital requirements.'],
    ],
    clientUse: [
      ['Separate motion from progress', 'Show which initiatives actually change the way the business works and which ones only add activity.'],
      ['Find the fork', 'Name whether the next moves reduce drag or protect old constraints.'],
      ['Sequence the work', 'Choose the first few moves that create options instead of launching a broad transformation program.'],
    ],
    previous: ['Previous: Field State', '/gpi-framework/field-state'],
    next: ['Next: Particle State', '/gpi-framework/particle-state'],
  },
  'particle-state': {
    slug: 'particle-state',
    title: 'Particle State',
    kicker: 'State / GPI 7-10',
    meta: 'heavy process / trapped knowledge / slow change',
    description: 'Particle State businesses have so much process, history, structure, and weight that even small changes become hard to move.',
    summary: [
      'Particle State is not always incompetence. Sometimes the weight exists for a reason: regulation, safety, capital, risk, or a business model that depends on stability.',
      'The danger is mismatch. A heavy business can survive in slow terrain. It gets exposed when the world starts asking for speed, learning, or a cleaner customer experience.',
    ],
    thesis: 'In Particle State, the business has weight. Sometimes that weight is a moat. Sometimes it is the reason the company cannot update what it already knows is wrong.',
    scale: [
      ['Score 1-3', 'The business has enough shared context, agency, and flexibility to move without turning every change into a campaign.'],
      ['Score 4-6', 'The system is mixed. Some movement is still possible, but legacy structure, incentives, or assets are starting to set the pace.'],
      ['Score 7-10', 'Decisions travel up and down. Knowledge sits in silos or veterans. Errors stay alive until they become expensive enough to force action.'],
      ['Watch for', 'Friction can become identity. The business protects the process even when the process is the problem.'],
    ],
    signals: [
      'A small change requires multiple committees, approvals, or budget cycles.',
      'Nobody knows the real workflow except the people who have been there for years.',
      'Customers tolerate pain because switching costs are worse.',
      'The company treats delay as normal, then builds reporting around the delay.',
      'Talent that wants to build leaves; talent that knows how to survive stays.',
      'The most profitable part of the model may be the gap, not the value creation.',
    ],
    examples: [
      ['Epic Systems', 'Deep healthcare lock-in where switching costs can exceed the pain of staying.'],
      ['Higher Education', 'Credential moats, tenure systems, accreditation, and institutional habits slow operating change.'],
      ['Government', 'Some friction is constitutional and intentional; the read depends heavily on terrain and mandate.'],
      ['Boeing', 'Safety, supplier, production, finance, and culture failures compounded across a very heavy system.'],
    ],
    clientUse: [
      ['Name the weight', 'Separate useful stability from dead process.'],
      ['Find the first release', 'Look for the smallest move that reduces lock-in or exposes hidden delay.'],
      ['Respect the risk', 'Do not prescribe speed to a system that cannot absorb the consequences yet.'],
    ],
    previous: ['Previous: Transition State', '/gpi-framework/transition-state'],
  },
  'decision-latency': {
    slug: 'decision-latency',
    title: 'Decision Latency',
    kicker: 'Dimension 1',
    meta: 'signal -> decision -> action',
    description: 'Decision Latency asks how long it takes the business to turn a real signal into a real move.',
    summary: [
      'Decision Latency is the gap between knowing something and doing something about it.',
      'Most businesses do not move slowly because people are lazy. They move slowly because the decision path was built to protect, defer, or spread responsibility until nobody has to own the call.',
    ],
    thesis: 'Every extra layer between signal and action is a tax. The business pays in time, context, energy, and lost options.',
    scale: [
      ['Score 1-3', 'Authority sits close to the work. Most decisions do not require escalation, and failing initiatives can be killed quickly.'],
      ['Score 4-6', 'Routine calls still move, but larger or politically exposed decisions start waiting for meetings, sponsors, or consensus.'],
      ['Score 7-10', 'Decisions travel upward to people far from the work, then back down after the context has already changed.'],
    ],
    signals: [
      'Budget shifts require more approval than the size or risk justifies.',
      'People wait for meetings to solve problems they already understand.',
      'Urgent work still follows the normal approval path.',
      'Decision rights are implied, political, or different depending on who asks.',
      'A failed initiative survives because nobody owns the decision to stop it.',
      'The business has more steering committees than steering capacity.',
    ],
    examples: [
      ['Stripe', 'Low latency: many product and API decisions can move through documented rules and distributed authority.'],
      ['Spotify', 'Low-to-mid latency: squad autonomy reduces routine escalation, though scale can add coordination drag.'],
      ['Comcast', 'Higher latency: voting control, executive layers, and legacy systems slow movement.'],
      ['Warner Bros. Discovery', 'Higher latency: merger integration and budget pressure route decisions through layers of protection.'],
    ],
    clientUse: [
      ['Draw the path', 'Map the real route from signal to decision to action.'],
      ['Price the wait', 'Name what does not happen while the business is waiting.'],
      ['Move rights closer', 'Clarify which decisions can be made near the work without creating unacceptable risk.'],
    ],
    next: ['Next: Error Correction', '/gpi-framework/error-correction'],
  },
  'error-correction': {
    slug: 'error-correction',
    title: 'Error Correction',
    kicker: 'Dimension 2',
    meta: 'mistake -> learning -> system update',
    description: 'Error Correction asks whether mistakes become learning or just become part of how the business works.',
    summary: [
      'The question is not whether the business makes mistakes. Every business does.',
      'The question is whether the mistake updates the system or gets renamed, explained away, and repeated until it becomes normal.',
    ],
    thesis: 'A mistake that updates the system is tuition. A mistake that keeps repeating is operating debt.',
    scale: [
      ['Score 1-3', 'Problems surface quickly, ownership is clear, fixes change the workflow, and the lesson travels.'],
      ['Score 4-6', 'Visible problems get fixed, but protected work, political mistakes, or cross-team failures still linger.'],
      ['Score 7-10', 'Problems are hidden, normalized, explained away, or fixed locally without changing the larger system.'],
    ],
    signals: [
      'The same failure appears in different departments with different names.',
      'Post-mortems produce documents but not changed behavior.',
      'People are punished for surfacing problems before they become visible externally.',
      'Customer complaints are treated as anecdotes instead of signal.',
      'Data says one thing and incentives reward another.',
      'The fix depends on one heroic person instead of the operating system.',
    ],
    examples: [
      ['Netflix', 'Fast correction: Qwikster was reversed quickly and later pivots showed willingness to change under pressure.'],
      ['Amazon', 'Fast correction: failed experiments can be killed while learning feeds new tools and systems.'],
      ['Northvolt', 'Slow correction: production issues and capital commitments compounded until the correction window narrowed sharply.'],
      ['Boeing', 'Slow correction: safety and production failures revealed errors that had accumulated across many layers.'],
    ],
    clientUse: [
      ['Trace recurrence', 'Look for the same problem repeating under different names.'],
      ['Separate blame from update', 'Ask whether the system changed or only the person responsible changed.'],
      ['Build the loop', 'Define how future errors will be noticed, fixed, and remembered.'],
    ],
    previous: ['Previous: Decision Latency', '/gpi-framework/decision-latency'],
    next: ['Next: Knowledge Location', '/gpi-framework/knowledge-location'],
  },
  'knowledge-location': {
    slug: 'knowledge-location',
    title: 'Knowledge Location',
    kicker: 'Dimension 3',
    meta: 'where the truth lives',
    description: 'Knowledge Location asks where the truth lives and whether the business can find it when the decision needs it.',
    summary: [
      'Knowledge can live in systems, documents, teams, leaders, vendors, rituals, or one person who has been there for twenty years.',
      'This dimension asks whether the company can find what it already knows without stopping the work to ask around.',
    ],
    thesis: 'When knowledge is trapped, every decision becomes a search problem. When knowledge is findable, the business can learn in public with itself.',
    scale: [
      ['Score 1-3', 'Knowledge is documented, searchable, shared, and close to the people making decisions.'],
      ['Score 4-6', 'Important knowledge exists, but people still depend on relationships, memory, or team-specific systems to find it.'],
      ['Score 7-10', 'Knowledge lives in silos, veterans, executives, vendors, spreadsheets, or informal workarounds.'],
    ],
    signals: [
      'A departing employee creates operational panic.',
      'People keep private files because the official system is not trusted.',
      'The source of truth depends on department, seniority, or location.',
      'New hires learn by shadowing because written knowledge is incomplete.',
      'Vendors understand the workflow better than internal teams.',
      'AI tools hallucinate because the underlying company context is scattered or stale.',
    ],
    examples: [
      ['GitLab', 'Low friction: handbook culture makes a large amount of operating knowledge available by default.'],
      ['Toyota', 'Strong local knowledge loops, though much of the capability is embodied in practice and training.'],
      ['Tesla', 'Higher risk: founder and key-person dependency can concentrate decision context.'],
      ['Legacy healthcare', 'Knowledge often spans EHRs, payers, clinicians, paper processes, and tribal workarounds.'],
    ],
    clientUse: [
      ['Locate the truth', 'Identify where the work is actually understood.'],
      ['Make it findable', 'Put the knowledge where people and agents can use it.'],
      ['Reduce key-person risk', 'Turn repeated explanations into durable working context.'],
    ],
    previous: ['Previous: Error Correction', '/gpi-framework/error-correction'],
    next: ['Next: Structural Lock-In', '/gpi-framework/structural-lock-in'],
  },
  'structural-lock-in': {
    slug: 'structural-lock-in',
    title: 'Structural Lock-In',
    kicker: 'Dimension 4',
    meta: 'how expensive change becomes',
    description: 'Structural Lock-In asks what the business is still forced to carry from earlier decisions.',
    summary: [
      'Lock-in is the accumulated cost of yesterday’s choices. Some of it is useful. Some of it becomes a cage.',
      'This dimension asks whether the company can move when the terrain changes or whether its own structure keeps pulling it back.',
    ],
    thesis: 'Every structure makes some moves easier and other moves harder. Structural Lock-In names the price of changing your mind.',
    scale: [
      ['Score 1-3', 'Systems are modular, contracts are flexible, decision rights are clear, and strategy can change without tearing down the company.'],
      ['Score 4-6', 'The business can still change, but old systems, contracts, channels, or politics make some moves slower than they should be.'],
      ['Score 7-10', 'Assets, debt, contracts, channels, politics, or platforms make the old path easier even when the old path is wrong.'],
    ],
    signals: [
      'The company knows what should change but cannot afford the transition.',
      'Legacy contracts decide the strategy more than customers do.',
      'The org chart protects the old business model.',
      'A platform, vendor, or facility has become the hidden boss.',
      'The business case for change dies under migration cost.',
      'People defend constraints as identity instead of treating them as design choices.',
    ],
    examples: [
      ['Apple', 'Moderate lock-in: ecosystem and hardware supply chain are constraints, but also part of the advantage.'],
      ['Walmart', 'Stores and distribution assets create both advantage and weight.'],
      ['Oracle', 'Legacy enterprise relationships and installed systems create durable but rigid lock-in.'],
      ['Airlines', 'Fleets, unions, gates, regulation, debt, and maintenance cycles constrain strategic freedom.'],
    ],
    clientUse: [
      ['Name constraints', 'Separate real constraints from inherited assumptions.'],
      ['Find reversible moves', 'Prioritize moves that create optionality before forcing a full pivot.'],
      ['Map exit cost', 'Make the cost of staying and the cost of changing visible together.'],
    ],
    previous: ['Previous: Knowledge Location', '/gpi-framework/knowledge-location'],
    next: ['Next: Talent Flow', '/gpi-framework/talent-flow'],
  },
  'talent-flow': {
    slug: 'talent-flow',
    title: 'Talent Flow',
    kicker: 'Dimension 5',
    meta: 'where capable people move',
    description: 'Talent Flow asks where capable people move, where they get stuck, and what that says about the business.',
    summary: [
      'Talent Flow is not just recruiting. It is whether capable people can move toward the real work without getting trapped by politics, roles, or managers protecting their own metrics.',
      'A company can have brilliant people and still waste talent if the structure teaches them to survive instead of build.',
    ],
    thesis: 'The business tells the truth through where capable people choose to spend their energy.',
    scale: [
      ['Score 1-3', 'People move toward problems, roles flex, learning is rewarded, and talent density compounds.'],
      ['Score 4-6', 'Strong people can still move, but role boundaries, manager incentives, or internal politics create drag.'],
      ['Score 7-10', 'People protect territory, high performers exit, roles harden, and survival skills replace building skills.'],
    ],
    signals: [
      'The best people are assigned to political work instead of important work.',
      'Internal transfers are harder than external hiring.',
      'People stay because leaving is hard, not because the work is alive.',
      'Managers hoard talent to protect their own metrics.',
      'Training exists but does not change role readiness.',
      'Exit interviews reveal the system already knew why people were leaving.',
    ],
    examples: [
      ['Costco', 'Strong retention and internal advancement show healthier flow than many retailers.'],
      ['Netflix', 'Keeper-test culture creates high talent density, but at the cost of comfort and long-term security.'],
      ['Consulting firms', 'Talent flow can be high but extractive if learning and burnout are poorly balanced.'],
      ['Legacy industrials', 'Deep expertise can become trapped if succession and documentation are weak.'],
    ],
    clientUse: [
      ['Map mobility', 'Show how people actually move across roles, projects, and constraints.'],
      ['Identify hoarding', 'Find where talent gets trapped by management incentives.'],
      ['Connect training to work', 'Turn training from event-based content into operating readiness.'],
    ],
    previous: ['Previous: Structural Lock-In', '/gpi-framework/structural-lock-in'],
    next: ['Next: Capital Intensity', '/gpi-framework/capital-intensity'],
  },
  'capital-intensity': {
    slug: 'capital-intensity',
    title: 'Capital Intensity',
    kicker: 'Dimension 6',
    meta: 'how much weight the strategy carries',
    description: 'Capital Intensity asks how much weight the strategy has to carry before it can move.',
    summary: [
      'Capital is not bad. Factories, fleets, data centers, stores, labs, and inventory can be the advantage.',
      'They can also make change painfully slow. This dimension asks how much the business has to spend, maintain, finance, or defend before strategy can move.',
    ],
    thesis: 'Every dollar embedded in heavy assets pulls on the next decision. The question is whether that pull creates advantage or traps the next move.',
    scale: [
      ['Score 1-3', 'Asset-light, modular, or flexible enough that strategy can change without stranding major capital.'],
      ['Score 4-6', 'The business carries meaningful assets or commitments, but still has enough flexibility to test, stage, or redirect capital.'],
      ['Score 7-10', 'Large fixed assets, debt, inventory, plants, fleets, labs, or compute commitments make movement expensive.'],
    ],
    signals: [
      'The company needs scale before the model can breathe.',
      'Debt service, capex, or depreciation quietly sets strategy.',
      'Leadership wants software speed inside hardware economics.',
      'A facility, fleet, or platform must stay utilized even when demand changes.',
      'The company cannot test small because the asset base is large.',
      'Forecast errors become balance-sheet problems.',
    ],
    examples: [
      ['Canva', 'Lower capital intensity: software economics allow faster movement and lower physical lock-in.'],
      ['TSMC', 'Extreme capital intensity that works because capability, trust, and geopolitical importance create advantage.'],
      ['Rivian', 'Manufacturing plants and vehicle economics create high capital drag despite software ambition.'],
      ['Data centers', 'AI infrastructure commitments can become advantage or trap depending on demand, utilization, and financing.'],
    ],
    clientUse: [
      ['Price the weight', 'Show how capital commitments constrain the next decision.'],
      ['Separate advantage from drag', 'Identify which assets create advantage and which only require defense.'],
      ['Stage the move', 'Design smaller tests that respect how much weight the business already carries.'],
    ],
    previous: ['Previous: Talent Flow', '/gpi-framework/talent-flow'],
    next: ['Next: Knowledge Velocity', '/gpi-framework/knowledge-velocity'],
  },
  'knowledge-velocity': {
    slug: 'knowledge-velocity',
    title: 'Knowledge Velocity',
    kicker: 'Dimension 7',
    meta: 'how fast learning changes behavior',
    description: 'Knowledge Velocity asks how fast new information becomes shared understanding and then changed behavior.',
    summary: [
      'Knowledge Velocity is not how much information the business has. It is how quickly useful information gets understood and changes what people do.',
      'In the AI age, this gets sharper because AI can accelerate bad context as easily as good context.',
    ],
    thesis: 'The gap between knowing and doing is where many businesses lose their future.',
    scale: [
      ['Score 1-3', 'Signals become shared context quickly, and shared context changes workflows, products, decisions, or customer handling.'],
      ['Score 4-6', 'The organization sees useful signals, but translation into priorities, workflows, or behavior is uneven.'],
      ['Score 7-10', 'The organization knows things but does not absorb them. Insight gets trapped in reports, teams, meetings, or tools.'],
    ],
    signals: [
      'Reads are produced but not used in decisions.',
      'Dashboards show the issue long before behavior changes.',
      'AI tools are added before the context layer is cleaned up.',
      'Lessons from one client, product, or market do not travel to the next.',
      'People debate facts because source systems disagree.',
      'The organization keeps rediscovering what it already learned.',
    ],
    examples: [
      ['Amazon', 'High velocity: customer, system, and experiment loops can convert knowledge into new ways of working.'],
      ['Roblox', 'High product learning loops, though monetization and infrastructure economics create drag.'],
      ['Traditional universities', 'Large knowledge stores, but slow conversion into operating change.'],
      ['Legacy public systems', 'Often rich in lived knowledge but weak in capture, retrieval, and system updates.'],
    ],
    clientUse: [
      ['Build behind-the-map notes', 'Connect raw data, observations, and context to decision-ready outputs.'],
      ['Version the read', 'Keep old and new analysis available so learning is visible.'],
      ['Feed the agent', 'Give AI tools structured, current context instead of scattered files and hope.'],
    ],
    previous: ['Previous: Capital Intensity', '/gpi-framework/capital-intensity'],
  },
};
