// Companies that have local GPI snapshots
// Slugs are lowercase, hyphenated versions of company names

export const companiesWithSnapshots: Set<string> = new Set(['tesla',
  'byd',
  'aldi',
  'avison young',
  'cbre',
  'jll',
  'mckinsey',
  'bain',
  'bcg',
  'ups',
  'amazon',
  'comcast',
  'wbd',
  'warner bros. discovery',
  'at&t',
  'att',
  'verizon',
  't-mobile',
  'charter',
  'lumen',
  'disney',
  'paramount',
  'fedex',
  'apple',
  'microsoft',
  'alphabet',
  'google',
  'meta',
  'walmart',
  "dick's sporting goods",
  'costco',
  'nvidia',
  'target',
  'home depot',
  'unitedhealth group',
  'unitedhealth',
  'cvs health',
  'cvs',
  'elevance health',
  'elevance',
  'cigna',
  'ford',
  'general motors',
  'gm',
  'stellantis',
  'xpo',
  'boeing',
  'lockheed martin',
  'rtx',
  'raytheon',
  'northrop grumman',
  'general dynamics',
  'berkshire hathaway',
  'state farm',
  'progressive',
  'allstate',
  'arthur j. gallagher',
  'blockbuster',
  'procter & gamble',
  'p&g',
  'pepsico',
  'pepsi',
  'coca-cola',
  'coke',
  'mars',
  'kenvue',
  'ibm',
  'oracle',
  'salesforce',
  'accenture',
  'hewlett packard enterprise',
  'hpe',
  'duke energy',
  'southern company',
  'nextera energy',
  'dominion energy',
  'ge vernova',
  'intel',
  'broadcom',
  'qualcomm',
  'netflix',
  'mars',
  'dominion-energy',
  'rtx',
  'kenvue',
  'procter-gamble',
  'lockheed-martin',
  'pixar',
  'elevance',
  'pepsico',
  'stellantis',
  'ge-vernova',
  'xpo',
  'northrop-grumman',
  'cvs',
  'hewlett-packard-enterprise',
  'coca-cola',
  'arthur-j-gallagher',
  'broadcom',
  'dicks-sporting-goods',
  'southern-company',
  'cigna',
  'unitedhealth',
  'state-farm',
  'general-dynamics',
  'allstate',
  'nextera-energy',
  'duke-energy',
  'general-motors',
  'qualcomm',
  'accenture',
  'amd',
  'synopsys',
  'hca-healthcare',
  'hca healthcare',
  'commonspirit-health',
  'commonspirit health',
  'ascension',
  'walgreens-boots-alliance',
  'walgreens boots alliance',
  'rite-aid',
  'rite aid',
  '3m',
  '3m company',
  'caterpillar',
  'caterpillar inc',
  'caterpillar inc.',
  'cardinal-health',
  'cardinal health',
  'honeywell',
  'tenet-healthcare',
  'prologis',
  'lennar',
  'lennar corporation',
  'ge-aerospace',
  'cencora',
  'siemens-usa',
  'dr-horton',
  'd.r. horton',
  'mckesson',
  'northwell-health',
  'northwell health',
  'databricks',
  'h-e-b',
  'winco-foods',
  'spacex',
  'wework',
  'chick-fil-a',
  'in-n-out-burger',
  'cargill',
  'publix',
  'revolut',
  'saks-global',
  'winco-foods',
  'walgreens-boots-alliance',
  'rite-aid',
  'chick-fil-a',
  'databricks',
  'in-n-out-burger',
  '3m',
  'caterpillar',
  'cardinal-health',
  'honeywell',
  'tenet-healthcare',
  'commonspirit-health',
  'h-e-b',
  'prologis',
  'hca-healthcare',
  'synopsys',
  'lennar',
  'ge-aerospace',
  'cencora',
  'ascension',
  'siemens-usa',
  'spacex',
  'dr-horton',
  'mckesson',
  'northwell-health',
  'cargill',
  'wework',
  'stripe',
  'spotify',
  'openai',
  'northvolt',
  'roblox',
  'microstrategy',
  'rivian',
  '23andme',
  'carvana',
  'koch industries',
  'koch-industries',
  'netflix-wbd-deal-analysis',
  'walmart-inc',
  'walmart-2026-02-01-complete',
  'pilot-company',
  'pilot company',
  'canva',
]);

export function hasSnapshot(companyName: string): boolean {
  return companiesWithSnapshots.has(companyName.toLowerCase());
}

export function getSnapshotSlug(companyName: string): string | null {
  const name = companyName.toLowerCase();
  if (!companiesWithSnapshots.has(name)) return null;

  // Map company names to their snapshot slugs
  const slugMap: Record<string, string> = {'disney': 'disney',
    'netflix': 'netflix',
    'tesla': 'tesla',
    'amazon': 'amazon',
    'boeing': 'boeing',
    'nvidia': 'nvidia',
    'walmart': 'walmart',
    'apple': 'apple',
    'meta': 'meta',
    'microsoft': 'microsoft',
    'alphabet': 'alphabet',
    'google': 'alphabet',
    // New additions
    'byd': 'byd',
    'costco': 'costco',
    'costco wholesale': 'costco',
    'costco wholesale corporation': 'costco',
    'intel': 'intel',
    'intel corporation': 'intel',
    'ups': 'ups',
    'united parcel service': 'ups',
    'fedex': 'fedex',
    'fedex corporation': 'fedex',
    'target': 'target',
    'target corporation': 'target',
    'ford': 'ford',
    'ford motor company': 'ford',
    'ford motor': 'ford',
    'blockbuster': 'blockbuster',
    'comcast': 'comcast',
    'comcast corporation': 'comcast',
    'progressive': 'progressive',
    'progressive corporation': 'progressive',
    'salesforce': 'salesforce',
    'salesforce.com': 'salesforce',
    'home depot': 'home-depot',
    'the home depot': 'home-depot',
    'gm': 'gm',
    'general motors': 'gm',
    'ibm': 'ibm',
    'oracle': 'oracle',
    'oracle corporation': 'oracle',
    'at&t': 'att',
    'att': 'att',
    'verizon': 'verizon',
    'verizon communications': 'verizon',
    'berkshire hathaway': 'berkshire-hathaway',
    'berkshire': 'berkshire-hathaway',
    'mars': 'mars',
    'mars, incorporated': 'mars',
    'dominion-energy': 'dominion-energy',
    'dominion energy': 'dominion-energy',
    'rtx': 'rtx',
    'rtx corporation (raytheon)': 'rtx',
    'kenvue': 'kenvue',
    'procter-gamble': 'procter-gamble',
    'procter & gamble': 'procter-gamble',
    'lockheed-martin': 'lockheed-martin',
    'lockheed martin': 'lockheed-martin',
    'pixar': 'pixar',
    'pixar animation studios': 'pixar',
    'elevance': 'elevance',
    'elevance health': 'elevance',
    'pepsico': 'pepsico',
    'stellantis': 'stellantis',
    'stellantis n.v.': 'stellantis',
    'ge-vernova': 'ge-vernova',
    'ge vernova': 'ge-vernova',
    'xpo': 'xpo',
    'xpo, inc.': 'xpo',
    'xpo,': 'xpo',
    'northrop-grumman': 'northrop-grumman',
    'northrop grumman': 'northrop-grumman',
    'cvs': 'cvs',
    'cvs health': 'cvs',
    'hewlett-packard-enterprise': 'hewlett-packard-enterprise',
    'hewlett packard enterprise': 'hewlett-packard-enterprise',
    'coca-cola': 'coca-cola',
    'arthur-j-gallagher': 'arthur-j-gallagher',
    'arthur j. gallagher & co.': 'arthur-j-gallagher',
    'broadcom': 'broadcom',
    'broadcom inc.': 'broadcom',
    'dicks-sporting-goods': 'dicks-sporting-goods',
    'dick\'s sporting goods': 'dicks-sporting-goods',
    'southern-company': 'southern-company',
    'southern company': 'southern-company',
    'southern': 'southern-company',
    'cigna': 'cigna',
    'the cigna group': 'cigna',
    'unitedhealth': 'unitedhealth',
    'unitedhealth group': 'unitedhealth',
    'state-farm': 'state-farm',
    'state farm': 'state-farm',
    'general-dynamics': 'general-dynamics',
    'general dynamics': 'general-dynamics',
    'allstate': 'allstate',
    'allstate corporation': 'allstate',
    'nextera-energy': 'nextera-energy',
    'nextera energy': 'nextera-energy',
    'duke-energy': 'duke-energy',
    'duke energy': 'duke-energy',
    'general-motors': 'general-motors',
    'qualcomm': 'qualcomm',
    'accenture': 'accenture',
    'amd': 'amd',
    'synopsys': 'synopsys',
    'hca-healthcare': 'hca-healthcare',
    'hca healthcare': 'hca-healthcare',
    'commonspirit-health': 'commonspirit-health',
    'commonspirit health': 'commonspirit-health',
    'ascension': 'ascension',
    'walgreens-boots-alliance': 'walgreens-boots-alliance',
    'walgreens boots alliance': 'walgreens-boots-alliance',
    'rite-aid': 'rite-aid',
    'rite aid': 'rite-aid',
    '3m': '3m',
    '3m company': '3m',
    'caterpillar': 'caterpillar',
    'caterpillar inc': 'caterpillar',
    'caterpillar inc.': 'caterpillar',
    'cardinal-health': 'cardinal-health',
    'cardinal health': 'cardinal-health',
    'honeywell': 'honeywell',
    'tenet-healthcare': 'tenet-healthcare',
    'tenet healthcare': 'tenet-healthcare',
    'prologis': 'prologis',
    'lennar': 'lennar',
    'lennar corporation': 'lennar',
    'ge-aerospace': 'ge-aerospace',
    'ge aerospace': 'ge-aerospace',
    'cencora': 'cencora',
    'siemens-usa': 'siemens-usa',
    'siemens usa': 'siemens-usa',
    'dr-horton': 'dr-horton',
    'dr horton': 'dr-horton',
    'd.r. horton': 'dr-horton',
    'mckesson': 'mckesson',
    'northwell-health': 'northwell-health',
    'northwell health': 'northwell-health',
    'databricks': 'databricks',
    'h-e-b': 'h-e-b',
    'h e b': 'h-e-b',
    'winco-foods': 'winco-foods',
    'winco foods': 'winco-foods',
    'spacex': 'spacex',
    'wework': 'wework',
    'chick-fil-a': 'chick-fil-a',
    'chick fil a': 'chick-fil-a',
    'in-n-out-burger': 'in-n-out-burger',
    'in n out burger': 'in-n-out-burger',
    'cargill': 'cargill',
    'publix': 'publix',
    'revolut': 'revolut',
    'saks-global': 'saks-global',
    'saks global': 'saks-global',
    'stripe': 'stripe',
    'spotify': 'spotify',
    'openai': 'openai',
    'northvolt': 'northvolt',
    'roblox': 'roblox',
    'microstrategy': 'microstrategy',
    'rivian': 'rivian',
    '23andme': '23andme',
    'carvana': 'carvana',
    'koch-industries': 'koch-industries',
    'koch industries': 'koch-industries',
    'netflix-wbd-deal-analysis': 'netflix-wbd-deal-analysis',
    'netflix wbd deal analysis': 'netflix-wbd-deal-analysis',
    'walmart-inc': 'walmart-inc',
    'walmart inc': 'walmart-inc',
    'walmart-2026-02-01-complete': 'walmart-2026-02-01-complete',
    'walmart 2026 02 01 complete': 'walmart-2026-02-01-complete',
    'pilot-company': 'pilot-company',
    'pilot company': 'pilot-company',
    'pilot': 'pilot-company',
    'canva': 'canva',
  };

  return slugMap[name] || null;
}
