// Companies that have local GPI snapshots
// Slugs are lowercase, hyphenated versions of company names

export const companiesWithSnapshots: Set<string> = new Set([
  'tesla',
  'byd',
  'aldi',
  'avison young',
  'cbre',
  'jll',
  'mckinsey',
  'bain',
  'bcg',
  'ups',
  'amazon',
  'comcast',
  'wbd',
  'warner bros. discovery',
  'at&t',
  'att',
  'verizon',
  't-mobile',
  'charter',
  'lumen',
  'disney',
  'paramount',
  'fedex',
  'apple',
  'microsoft',
  'alphabet',
  'google',
  'meta',
  'walmart',
  "dick's sporting goods",
  'costco',
  'nvidia',
  'target',
  'home depot',
  'unitedhealth group',
  'unitedhealth',
  'cvs health',
  'cvs',
  'elevance health',
  'elevance',
  'cigna',
  'ford',
  'general motors',
  'gm',
  'stellantis',
  'xpo',
  'boeing',
  'lockheed martin',
  'rtx',
  'raytheon',
  'northrop grumman',
  'general dynamics',
  'berkshire hathaway',
  'state farm',
  'progressive',
  'allstate',
  'arthur j. gallagher',
  'blockbuster',
  'procter & gamble',
  'p&g',
  'pepsico',
  'pepsi',
  'coca-cola',
  'coke',
  'mars',
  'kenvue',
  'ibm',
  'oracle',
  'salesforce',
  'accenture',
  'hewlett packard enterprise',
  'hpe',
  'duke energy',
  'southern company',
  'nextera energy',
  'dominion energy',
  'ge vernova',
  'intel',
  'broadcom',
  'qualcomm',
  'netflix',
]);

export function hasSnapshot(companyName: string): boolean {
  return companiesWithSnapshots.has(companyName.toLowerCase());
}

export function getSnapshotSlug(companyName: string): string | null {
  const name = companyName.toLowerCase();
  if (!companiesWithSnapshots.has(name)) return null;

  // Map company names to their snapshot slugs
  const slugMap: Record<string, string> = {
    'disney': 'disney',
    'netflix': 'netflix',
    'tesla': 'tesla',
    'amazon': 'amazon',
    'boeing': 'boeing',
    'nvidia': 'nvidia',
    'walmart': 'walmart',
    'apple': 'apple',
    'meta': 'meta',
    'microsoft': 'microsoft',
    'alphabet': 'alphabet',
    'google': 'alphabet',
  };

  return slugMap[name] || null;
}
