// Companies that have local GPI snapshots
// Slugs are lowercase, hyphenated versions of company names

export const companiesWithSnapshots: Set<string> = new Set(['tesla',
  'byd',
  'aldi',
  'avison young',
  'cbre',
  'jll',
  'mckinsey',
  'bain',
  'bcg',
  'ups',
  'amazon',
  'comcast',
  'wbd',
  'warner bros. discovery',
  'at&t',
  'att',
  'verizon',
  't-mobile',
  'charter',
  'lumen',
  'disney',
  'paramount',
  'fedex',
  'apple',
  'microsoft',
  'alphabet',
  'google',
  'meta',
  'walmart',
  "dick's sporting goods",
  'costco',
  'nvidia',
  'target',
  'home depot',
  'unitedhealth group',
  'unitedhealth',
  'cvs health',
  'cvs',
  'elevance health',
  'elevance',
  'cigna',
  'ford',
  'general motors',
  'gm',
  'stellantis',
  'xpo',
  'boeing',
  'lockheed martin',
  'rtx',
  'raytheon',
  'northrop grumman',
  'general dynamics',
  'berkshire hathaway',
  'state farm',
  'progressive',
  'allstate',
  'arthur j. gallagher',
  'blockbuster',
  'procter & gamble',
  'p&g',
  'pepsico',
  'pepsi',
  'coca-cola',
  'coke',
  'mars',
  'kenvue',
  'ibm',
  'oracle',
  'salesforce',
  'accenture',
  'hewlett packard enterprise',
  'hpe',
  'duke energy',
  'southern company',
  'nextera energy',
  'dominion energy',
  'ge vernova',
  'intel',
  'broadcom',
  'qualcomm',
  'netflix',
  'mars',
  'dominion-energy',
  'rtx',
  'kenvue',
  'procter-gamble',
  'lockheed-martin',
  'pixar',
  'elevance',
  'pepsico',
  'stellantis',
  'ge-vernova',
  'xpo',
  'northrop-grumman',
  'cvs',
  'hewlett-packard-enterprise',
  'coca-cola',
  'arthur-j-gallagher',
  'broadcom',
  'dicks-sporting-goods',
  'southern-company',
  'cigna',
  'unitedhealth',
  'state-farm',
  'general-dynamics',
  'allstate',
  'nextera-energy',
  'duke-energy',
  'general-motors',
  'qualcomm',
  'accenture',
  'amd',
]);

export function hasSnapshot(companyName: string): boolean {
  return companiesWithSnapshots.has(companyName.toLowerCase());
}

export function getSnapshotSlug(companyName: string): string | null {
  const name = companyName.toLowerCase();
  if (!companiesWithSnapshots.has(name)) return null;

  // Map company names to their snapshot slugs
  const slugMap: Record<string, string> = {'disney': 'disney',
    'netflix': 'netflix',
    'tesla': 'tesla',
    'amazon': 'amazon',
    'boeing': 'boeing',
    'nvidia': 'nvidia',
    'walmart': 'walmart',
    'apple': 'apple',
    'meta': 'meta',
    'microsoft': 'microsoft',
    'alphabet': 'alphabet',
    'google': 'alphabet',
    // New additions
    'byd': 'byd',
    'costco': 'costco',
    'costco wholesale': 'costco',
    'costco wholesale corporation': 'costco',
    'intel': 'intel',
    'intel corporation': 'intel',
    'ups': 'ups',
    'united parcel service': 'ups',
    'fedex': 'fedex',
    'fedex corporation': 'fedex',
    'target': 'target',
    'target corporation': 'target',
    'ford': 'ford',
    'ford motor company': 'ford',
    'ford motor': 'ford',
    'blockbuster': 'blockbuster',
    'comcast': 'comcast',
    'comcast corporation': 'comcast',
    'progressive': 'progressive',
    'progressive corporation': 'progressive',
    'salesforce': 'salesforce',
    'salesforce.com': 'salesforce',
    'home depot': 'home-depot',
    'the home depot': 'home-depot',
    'gm': 'gm',
    'general motors': 'gm',
    'ibm': 'ibm',
    'oracle': 'oracle',
    'oracle corporation': 'oracle',
    'at&t': 'att',
    'att': 'att',
    'verizon': 'verizon',
    'verizon communications': 'verizon',
    'berkshire hathaway': 'berkshire-hathaway',
    'berkshire': 'berkshire-hathaway',
    'mars': 'mars',
    'mars, incorporated': 'mars',
    'dominion-energy': 'dominion-energy',
    'dominion energy': 'dominion-energy',
    'rtx': 'rtx',
    'rtx corporation (raytheon)': 'rtx',
    'kenvue': 'kenvue',
    'procter-gamble': 'procter-gamble',
    'procter & gamble': 'procter-gamble',
    'lockheed-martin': 'lockheed-martin',
    'lockheed martin': 'lockheed-martin',
    'pixar': 'pixar',
    'pixar animation studios': 'pixar',
    'elevance': 'elevance',
    'elevance health': 'elevance',
    'pepsico': 'pepsico',
    'stellantis': 'stellantis',
    'stellantis n.v.': 'stellantis',
    'ge-vernova': 'ge-vernova',
    'ge vernova': 'ge-vernova',
    'xpo': 'xpo',
    'xpo, inc.': 'xpo',
    'xpo,': 'xpo',
    'northrop-grumman': 'northrop-grumman',
    'northrop grumman': 'northrop-grumman',
    'cvs': 'cvs',
    'cvs health': 'cvs',
    'hewlett-packard-enterprise': 'hewlett-packard-enterprise',
    'hewlett packard enterprise': 'hewlett-packard-enterprise',
    'coca-cola': 'coca-cola',
    'arthur-j-gallagher': 'arthur-j-gallagher',
    'arthur j. gallagher & co.': 'arthur-j-gallagher',
    'broadcom': 'broadcom',
    'broadcom inc.': 'broadcom',
    'dicks-sporting-goods': 'dicks-sporting-goods',
    'dick\'s sporting goods': 'dicks-sporting-goods',
    'southern-company': 'southern-company',
    'southern company': 'southern-company',
    'southern': 'southern-company',
    'cigna': 'cigna',
    'the cigna group': 'cigna',
    'unitedhealth': 'unitedhealth',
    'unitedhealth group': 'unitedhealth',
    'state-farm': 'state-farm',
    'state farm': 'state-farm',
    'general-dynamics': 'general-dynamics',
    'general dynamics': 'general-dynamics',
    'allstate': 'allstate',
    'allstate corporation': 'allstate',
    'nextera-energy': 'nextera-energy',
    'nextera energy': 'nextera-energy',
    'duke-energy': 'duke-energy',
    'duke energy': 'duke-energy',
    'general-motors': 'general-motors',
    'qualcomm': 'qualcomm',
    'accenture': 'accenture',
    'amd': 'amd',
  };

  return slugMap[name] || null;
}
