// Parsed snapshot content from local brain
// Structure matches the markdown snapshot format

export interface DimensionScore {
  dimension: string;
  score: number;
  explanation: string;
}

export interface CompanySnapshot {
  slug: string;
  name: string;
  analysisDate: string;
  gpiScore: number;
  state: string;
  ticker?: string;
  marketCap?: string;
  employees?: number;
  revenue?: string;
  founded?: number;
  dimensions: DimensionScore[];
  pattern: string;
  patternDescription: string;
  keyNumbers: string[];
  enablers: string[];
  friction: string[];
  quotable?: string;
  sources?: { title: string; url: string }[];
}

export const snapshotsContent: Record<string, CompanySnapshot> = {
  'disney': {
    slug: 'disney',
    name: 'Disney',
    analysisDate: '2026-01-16',
    gpiScore: 6.7,
    state: 'Transitioning (upper)',
    ticker: 'DIS',
    marketCap: '~$204B',
    employees: 231000,
    revenue: '$94.4B (FY2025)',
    founded: 1923,
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: 'Massive bureaucracy across Parks, Studios, Streaming, ESPN, Linear TV. Iger return needed to undo Chapek-era mistakes.' },
      { dimension: 'Error Correction', score: 6, explanation: 'Disney+ finally profitable after 3+ years. Correction capacity exists but cycle is slow. Layoffs reactive.' },
      { dimension: 'Knowledge Location', score: 7, explanation: 'Highly centralized. Imagineering has autonomy but major decisions require executive approval.' },
      { dimension: 'Structural Lock-In', score: 7, explanation: 'Parks require massive capital. ESPN decline (cord-cutting) creates strategic tension. IP exploitation limits risk-taking.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'Internal politics per Glassdoor. Layoffs without retention effort. "Political and toxic" culture in areas.' },
      { dimension: 'Capital Intensity', score: 8, explanation: 'Parks, cruise ships, content production. Treasure cruise line adds fixed costs. Content arms race.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: 'Siloed divisions (ESPN, Marvel, Pixar, Parks). Knowledge trapped in silos despite IP synergy.' },
    ],
    pattern: 'Managed Decline of Empire',
    patternDescription: 'Disney is too big and too capital-intensive to truly transform. Now optimizing for profitability within existing structure rather than reinvention. The dual burden: Streaming pivot worked but created content costs ON TOP OF infrastructure costs. Parks are both strength (unique moat) and weakness (capital anchor). Unlike Netflix (3.25), Disney cannot move fast because physical assets and linear TV anchor it to legacy operations.',
    keyNumbers: [
      'Streaming profit: $336M (finally profitable)',
      'Disney+ subscribers: 126M globally',
      'Cost savings target: $7.5B',
      'Jobs eliminated since 2023: 8,000+',
      'Iger compensation: $41.1M (30% increase)',
      '5-year market cap CAGR: -6.32%',
    ],
    enablers: [
      'Streaming profitable',
      'Strong IP portfolio (Marvel, Star Wars, Pixar, Disney Animation)',
      'Parks recovery post-COVID',
      'Iger stability',
      'Cost discipline improving',
    ],
    friction: [
      'ESPN decline (cord-cutting accelerating)',
      'Parks/cruise capital requirements',
      'Internal politics at SVP+ level',
      'CEO succession uncertainty (2026)',
      'Massive bureaucracy',
    ],
    quotable: 'Disney is optimizing for profitability within its existing structure rather than reinventing itself. The streaming pivot worked, but the parks, cruise ships, and linear TV create gravitational pull that Netflix will never feel.',
  },

  'netflix': {
    slug: 'netflix',
    name: 'Netflix',
    analysisDate: '2026-01-16',
    gpiScore: 3.25,
    state: 'Field',
    ticker: 'NFLX',
    marketCap: '~$380B',
    employees: 13000,
    revenue: '$39B (FY2025)',
    founded: 1997,
    dimensions: [
      { dimension: 'Decision Latency', score: 3, explanation: 'Flat org. "Context not control" culture. Decisions pushed to informed employees. No committees for most decisions.' },
      { dimension: 'Error Correction', score: 3, explanation: 'Killed Qwikster in 23 days. Password sharing crackdown succeeded after initial resistance. Ad tier pivot within 12 months.' },
      { dimension: 'Knowledge Location', score: 3, explanation: 'Radical transparency. Information flows freely. The "Netflix Culture Deck" codified knowledge sharing.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'No physical infrastructure. Content library is the main lock-in, but can be adjusted annually.' },
      { dimension: 'Talent Flow', score: 3, explanation: '"Keeper test" ensures high performers. Generous severance. No "brilliant jerks." Top of market pay.' },
      { dimension: 'Capital Intensity', score: 4, explanation: 'Content spend is high ($17B) but flexible year-to-year unlike physical assets.' },
      { dimension: 'Knowledge Velocity', score: 3, explanation: 'A/B testing culture. Data-driven decisions. Algorithm improvements compound.' },
    ],
    pattern: 'Culture as Infrastructure',
    patternDescription: 'Netflix built organizational software (culture) instead of organizational hardware (bureaucracy). The culture deck is their operating system. This is why they can move fast at scale. The "no rules" approach works because they hired adults and gave them context. Low GPI is not luck, it is architecture.',
    keyNumbers: [
      'Subscribers: 301M+ globally',
      'Content spend: $17B annually',
      'Revenue per employee: $3M',
      'Ad tier: 70M+ MAU (fastest growing)',
      'Password crackdown: +13M subscribers Q2 2024',
      'Market cap 5Y CAGR: +18%',
    ],
    enablers: [
      'No physical assets to maintain',
      'Culture that attracts talent',
      'Data/algorithm advantage',
      'Global scale with local content',
      'Ad tier growth runway',
    ],
    friction: [
      'Content cost inflation',
      'Competition for talent',
      'Saturation in core markets',
      'Live sports absent (for now)',
      'Founder transition (Hastings stepped back)',
    ],
    quotable: 'Netflix built organizational software instead of organizational hardware. The culture deck is their operating system. Low GPI is not luck, it is architecture.',
  },

  'tesla': {
    slug: 'tesla',
    name: 'Tesla',
    analysisDate: '2026-01-13',
    gpiScore: 6.8,
    state: 'Transitioning (upper)',
    ticker: 'TSLA',
    marketCap: '~$800B',
    employees: 140000,
    revenue: '$97B (FY2025)',
    founded: 2003,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Musk can decide instantly. But organization increasingly bureaucratic. Factory decisions fast, corporate slow.' },
      { dimension: 'Error Correction', score: 6, explanation: 'Cybertruck delays (years). FSD promises vs reality. But manufacturing iteration is excellent.' },
      { dimension: 'Knowledge Location', score: 7, explanation: 'Musk-dependent. Key decisions require his attention. Brain drain to SpaceX, xAI, etc.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: 'Gigafactories are massive fixed assets. Supercharger network. Vertical integration.' },
      { dimension: 'Talent Flow', score: 7, explanation: 'High turnover. Musk style polarizing. Best talent often leaves for other Musk ventures.' },
      { dimension: 'Capital Intensity', score: 8, explanation: 'Factories, battery production, robotaxi development. Massive capex requirements.' },
      { dimension: 'Knowledge Velocity', score: 7, explanation: 'Siloed between auto, energy, AI. Over-the-air updates are bright spot.' },
    ],
    pattern: 'Founder-Dependent Calcification',
    patternDescription: 'Tesla succeeded because Musk could override bureaucracy. Now the organization is calcifying around that dependency. The company moves fast when Musk is engaged, slowly when he is not. This is unsustainable at scale. Compare to BYD (3.4) which built systems, not dependence.',
    keyNumbers: [
      'Deliveries: 1.8M vehicles (2025)',
      'Energy storage: 15 GWh deployed',
      'Superchargers: 50,000+ globally',
      'R&D spend: $4B annually',
      'Musk time split: Tesla, SpaceX, xAI, X, Neuralink',
      'Stock volatility: 3x S&P average',
    ],
    enablers: [
      'Brand strength',
      'Supercharger network moat',
      'Manufacturing innovation (gigacasting)',
      'Software/OTA advantage',
      'Energy business growth',
    ],
    friction: [
      'Musk distraction/dependency',
      'China competition (BYD)',
      'Aging Model 3/Y lineup',
      'FSD liability overhang',
      'Talent retention issues',
    ],
    quotable: 'Tesla succeeded because Musk could override bureaucracy. Now the organization is calcifying around that dependency. The company moves fast when Musk is engaged, slowly when he is not.',
  },

  'amazon': {
    slug: 'amazon',
    name: 'Amazon',
    analysisDate: '2026-01-16',
    gpiScore: 3.55,
    state: 'Transitioning (lower)',
    ticker: 'AMZN',
    marketCap: '~$2.1T',
    employees: 1500000,
    revenue: '$620B (FY2025)',
    founded: 1994,
    dimensions: [
      { dimension: 'Decision Latency', score: 3, explanation: 'Two-pizza teams. "Disagree and commit." Single-threaded leaders. Day 1 culture still enforced.' },
      { dimension: 'Error Correction', score: 3, explanation: 'Fire Phone killed fast. Constant experimentation. "Failure and invention are inseparable twins."' },
      { dimension: 'Knowledge Location', score: 4, explanation: '6-page memos force clarity. But scale creates silos. AWS vs Retail friction.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Fulfillment centers are fixed but provide moat. AWS infrastructure is the business.' },
      { dimension: 'Talent Flow', score: 4, explanation: 'Up or out culture. High bar hiring. But warehouse turnover is 150%+.' },
      { dimension: 'Capital Intensity', score: 4, explanation: 'Massive capex but generates cash. AWS margins fund experiments.' },
      { dimension: 'Knowledge Velocity', score: 3, explanation: 'Internal tech sharing. AWS born from internal tools. Data obsession.' },
    ],
    pattern: 'Scale Without Calcification',
    patternDescription: 'Amazon maintains startup metabolism at trillion-dollar scale through deliberate mechanisms: two-pizza teams, 6-page memos, single-threaded ownership. Bezos built the operating system before he needed it. The "Day 1" philosophy is not a slogan, it is enforcement against entropy.',
    keyNumbers: [
      'AWS revenue: $100B+ annually',
      'Prime members: 200M+ globally',
      'Fulfillment centers: 1,000+',
      'Same-day delivery cities: 90+',
      'R&D spend: $85B (most in world)',
      'Two-pizza teams: thousands',
    ],
    enablers: [
      'AWS cash generation',
      'Prime flywheel',
      'Logistics moat',
      'Day 1 culture enforcement',
      'Willingness to cannibalize',
    ],
    friction: [
      'Antitrust pressure',
      'Labor relations',
      'Scale itself (1.5M employees)',
      'AWS growth deceleration',
      'Jassy vs Bezos leadership style',
    ],
    quotable: 'Amazon maintains startup metabolism at trillion-dollar scale through deliberate mechanisms. Bezos built the operating system before he needed it.',
  },

  'boeing': {
    slug: 'boeing',
    name: 'Boeing',
    analysisDate: '2026-01-19',
    gpiScore: 7.75,
    state: 'Particle',
    ticker: 'BA',
    marketCap: '~$120B',
    employees: 170000,
    revenue: '$78B (FY2025)',
    founded: 1916,
    dimensions: [
      { dimension: 'Decision Latency', score: 8, explanation: 'Multiple fatal decisions took years to address. 737 MAX grounding lasted 20 months. Safety culture eroded over decades.' },
      { dimension: 'Error Correction', score: 9, explanation: 'MCAS failures killed 346 people. Door plug blowout in 2024. Whistleblower retaliation. Errors compound.' },
      { dimension: 'Knowledge Location', score: 8, explanation: 'Engineering expertise hollowed out. Outsourced to suppliers. McDonnell Douglas finance culture won.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: 'Defense contracts, supplier dependencies, union agreements, regulatory oversight all limit options.' },
      { dimension: 'Talent Flow', score: 7, explanation: 'Engineers leaving. Reputation damaged. Hard to recruit safety-focused talent when safety is compromised.' },
      { dimension: 'Capital Intensity', score: 8, explanation: 'Aircraft development costs $10B+. Factories are fixed. R&D cycles are decades.' },
      { dimension: 'Knowledge Velocity', score: 7, explanation: 'Siloed between commercial, defense, space. Lessons not shared. Safety learnings lost.' },
    ],
    pattern: 'The Engineering Culture That Finance Ate',
    patternDescription: 'Boeing was once an engineering company that happened to have accountants. The McDonnell Douglas merger inverted this. Cost-cutting replaced safety culture. Stock buybacks replaced R&D. The 737 MAX disasters were not anomalies, they were the system working as redesigned. This is what happens when you optimize for quarterly earnings in an industry where errors kill people.',
    keyNumbers: [
      '737 MAX deaths: 346 people',
      'Stock buybacks (2013-2019): $43B',
      'Quality escapes (2024): 400+',
      'CEO turnover: 3 in 5 years',
      'Market share vs Airbus: declining',
      'Cash burn (2024): $8B',
    ],
    enablers: [
      'Defense contracts provide floor',
      'Duopoly with Airbus (no alternatives)',
      'Existing order backlog',
      'New CEO from outside',
      'FAA forcing changes',
    ],
    friction: [
      'Destroyed safety culture',
      'Engineering brain drain',
      'Supplier quality issues',
      'Union tensions',
      'Criminal liability overhang',
      'Customer trust erosion',
    ],
    quotable: 'Boeing was once an engineering company that happened to have accountants. The McDonnell Douglas merger inverted this. The 737 MAX disasters were not anomalies, they were the system working as redesigned.',
  },

  'nvidia': {
    slug: 'nvidia',
    name: 'NVIDIA',
    analysisDate: '2026-01-18',
    gpiScore: 3.55,
    state: 'Transitioning (lower)',
    ticker: 'NVDA',
    marketCap: '~$3T',
    employees: 30000,
    revenue: '$130B (FY2025)',
    founded: 1993,
    dimensions: [
      { dimension: 'Decision Latency', score: 3, explanation: 'Jensen Huang maintains founder control. "No 1:1s" policy forces group decisions. Flat structure despite scale.' },
      { dimension: 'Error Correction', score: 3, explanation: 'Pivoted from gaming to AI before market saw it. Crypto mining bust absorbed quickly. Continuous architecture iteration.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Jensen is the knowledge hub but pushes context down. CUDA ecosystem is institutional knowledge.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Fabless model provides flexibility. TSMC dependency is risk but not rigidity.' },
      { dimension: 'Talent Flow', score: 3, explanation: 'Top AI talent wants to work here. Stock appreciation helps retention. "Founders mentality" culture.' },
      { dimension: 'Capital Intensity', score: 4, explanation: 'Fabless means low capex. R&D is the spend, which is flexible.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'CUDA platform creates learning loops. Developer ecosystem compounds. Architecture generations every 2 years.' },
    ],
    pattern: 'The Founder\'s Flat',
    patternDescription: 'Jensen Huang built a company where the founder can still touch every major decision without creating bottlenecks. The "no 1:1s" policy forces information into the open. The CUDA ecosystem is a moat that compounds. NVIDIA succeeded not by building hardware but by building a platform that makes switching costs astronomical.',
    keyNumbers: [
      'Data center revenue: $100B+ (FY2025)',
      'Gross margin: 75%+',
      'CUDA developers: 4M+',
      'AI training market share: 80%+',
      'R&D spend: $10B annually',
      'Revenue per employee: $4.3M',
    ],
    enablers: [
      'AI demand explosion',
      'CUDA moat (20 years of ecosystem)',
      'Jensen leadership',
      'Fabless flexibility',
      'Software + hardware integration',
    ],
    friction: [
      'China export restrictions',
      'Customer concentration (hyperscalers)',
      'AMD/Intel competition',
      'Custom silicon threat (Google TPU, Amazon)',
      'Jensen key-man risk',
    ],
    quotable: 'NVIDIA succeeded not by building hardware but by building a platform that makes switching costs astronomical. The CUDA ecosystem is a moat that compounds.',
  },

  'walmart': {
    slug: 'walmart',
    name: 'Walmart',
    analysisDate: '2026-01-18',
    gpiScore: 4.65,
    state: 'Transitioning',
    ticker: 'WMT',
    marketCap: '~$600B',
    employees: 2100000,
    revenue: '$680B (FY2025)',
    founded: 1962,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Store managers have real authority. But corporate decisions slower. Doug McMillon pushes speed.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Jet.com acquisition failed but learned from it. E-commerce pivot working. Walmart+ growing.' },
      { dimension: 'Knowledge Location', score: 5, explanation: 'Bentonville HQ still central but technology enabling store-level intelligence.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: '4,700 US stores are fixed but also advantage (last-mile fulfillment).' },
      { dimension: 'Talent Flow', score: 5, explanation: 'Tech talent improving. But frontline turnover high. Two workforces.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'Stores are capex but generate cash. Automation investments ongoing.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Data advantage from scale. Supply chain intelligence. But silos between digital/physical.' },
    ],
    pattern: 'Scale as Transformation Platform',
    patternDescription: 'Walmart is using its physical footprint as an advantage rather than fighting it. Stores become fulfillment centers. Parking lots become pickup zones. The same scale that should calcify them is being repurposed. This is rare: usually physical assets become anchors. Walmart is making them accelerants.',
    keyNumbers: [
      'US stores: 4,700+',
      'E-commerce growth: 20%+ annually',
      'Walmart+ members: 25M+',
      'Pickup/delivery orders: 50%+ of e-commerce',
      'Same-day delivery reach: 80% of US',
      'Automation investment: $14B (3 years)',
    ],
    enablers: [
      'Physical footprint as fulfillment network',
      'Grocery anchor (65% of revenue)',
      'Advertising business ($4B+)',
      'McMillon leadership continuity',
      'Scale cost advantages',
    ],
    friction: [
      'Amazon competition',
      'Labor costs rising',
      'Store refresh capex',
      'International struggles',
      '2.1M employees to transform',
    ],
    quotable: 'Walmart is using its physical footprint as an advantage rather than fighting it. The same scale that should calcify them is being repurposed.',
  },

  'apple': {
    slug: 'apple',
    name: 'Apple',
    analysisDate: '2026-01-18',
    gpiScore: 4.30,
    state: 'Transitioning',
    ticker: 'AAPL',
    marketCap: '~$3.5T',
    employees: 164000,
    revenue: '$400B (FY2025)',
    founded: 1976,
    dimensions: [
      { dimension: 'Decision Latency', score: 4, explanation: 'Tim Cook runs tight ship. But iPhone dependency means careful iteration. Big bets are rare.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Butterfly keyboard fixed (eventually). Car project killed after $10B. Slow but eventual.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Functional org structure keeps knowledge in silos by design. Services group growing.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: 'iPhone is 50%+ of revenue. Ecosystem lock-in is the business model.' },
      { dimension: 'Talent Flow', score: 4, explanation: 'Still attracts top talent. But "innovation" culture questioned. Jony Ive left.' },
      { dimension: 'Capital Intensity', score: 4, explanation: 'Capex is supplier-funded largely. Services high margin. Hardware supply chain mastery.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: 'Silos by design limit cross-pollination. But integration is the product.' },
    ],
    pattern: 'Iteration Machine at the Crossroads',
    patternDescription: 'Apple perfected iterative improvement. Each iPhone slightly better. Each Mac slightly faster. But this machine struggles with category creation. The car is dead. The headset is niche. AI is late. When the core product (iPhone) saturates, the iteration machine needs a new target. Apple Intelligence is the bet.',
    keyNumbers: [
      'iPhone revenue: $200B+ annually',
      'Services revenue: $100B+ annually',
      'Installed base: 2.2B active devices',
      'R&D spend: $30B annually',
      'Gross margin: 45%+',
      'Car project cost: $10B (cancelled)',
    ],
    enablers: [
      'Ecosystem lock-in',
      'Services growth',
      'Brand premium',
      'Supply chain mastery',
      'Cash generation ($100B+ annually)',
    ],
    friction: [
      'iPhone saturation',
      'China market risk',
      'AI catch-up mode',
      'Regulatory pressure (App Store)',
      'Post-Jobs innovation questions',
    ],
    quotable: 'Apple perfected iterative improvement. But this machine struggles with category creation. When the core product saturates, the iteration machine needs a new target.',
  },

  'meta': {
    slug: 'meta',
    name: 'Meta',
    analysisDate: '2026-01-18',
    gpiScore: 4.25,
    state: 'Transitioning',
    ticker: 'META',
    marketCap: '~$1.4T',
    employees: 72000,
    revenue: '$160B (FY2025)',
    founded: 2004,
    dimensions: [
      { dimension: 'Decision Latency', score: 4, explanation: 'Zuckerberg controls. Can make big bets fast (Reality Labs). But org growing bureaucratic.' },
      { dimension: 'Error Correction', score: 4, explanation: '"Year of Efficiency" worked. Metaverse pivot adjusted (not abandoned). Threads launched fast.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Zuckerberg-centric but pushing AI across org. Reality Labs siloed.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Ad model is the lock-in. But proven ability to pivot (mobile, Stories, Reels).' },
      { dimension: 'Talent Flow', score: 5, explanation: 'Layoffs reset. AI talent competitive with Google/OpenAI. Reality Labs brain drain.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'Reality Labs burns $15B+ annually. AI infrastructure massive. Ads fund everything.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Open source strategy (Llama) spreads knowledge. But family of apps still somewhat siloed.' },
    ],
    pattern: 'The Expensive Pivot',
    patternDescription: 'Meta is betting $15B+ annually that the metaverse matters while simultaneously winning at AI. Zuckerberg has the control and cash to sustain expensive pivots. The "Year of Efficiency" proved the company can cut when needed. The question: is Reality Labs a visionary bet or an expensive distraction?',
    keyNumbers: [
      'Daily active users: 3.2B across apps',
      'Reality Labs losses: $15B+ annually',
      'AI capex: $40B+ (2025)',
      'Llama downloads: 700M+',
      'Headcount cut: 21,000 (2023)',
      'Revenue per employee: $2.2M',
    ],
    enablers: [
      'Ad business cash generation',
      'Zuckerberg control (voting shares)',
      'AI model leadership (Llama)',
      '3B+ user base',
      'Proven pivot ability',
    ],
    friction: [
      'Reality Labs cash burn',
      'TikTok competition (Reels)',
      'Regulatory overhang',
      'Apple ATT impact (recovering)',
      'Reputation/trust issues',
    ],
    quotable: 'Meta is betting $15B+ annually that the metaverse matters while simultaneously winning at AI. The "Year of Efficiency" proved the company can cut when needed.',
  },

  'microsoft': {
    slug: 'microsoft',
    name: 'Microsoft',
    analysisDate: '2026-01-18',
    gpiScore: 4.65,
    state: 'Transitioning',
    ticker: 'MSFT',
    marketCap: '~$3T',
    employees: 228000,
    revenue: '$260B (FY2025)',
    founded: 1975,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Nadella transformed culture but scale creates friction. Cloud decisions fast, legacy slower.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Windows Phone killed. LinkedIn pivoted. Azure grew from internal need. Can correct, not always fast.' },
      { dimension: 'Knowledge Location', score: 5, explanation: '"One Microsoft" reduced silos but 228K employees means knowledge pockets.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: 'Enterprise relationships are moat and lock-in. Office 365 stickiness. Azure switching costs.' },
      { dimension: 'Talent Flow', score: 4, explanation: 'AI talent competitive. Copilot team growing. But size means politics.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'Azure capex massive. But generates returns. Activision was $69B.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: 'GitHub, LinkedIn data advantages. But cross-product integration still evolving.' },
    ],
    pattern: 'Conscious Mass Reduction',
    patternDescription: 'Nadella took a calcifying giant and made it move again. Not by shrinking but by changing the culture. "Growth mindset" replaced "know-it-all" culture. The OpenAI partnership was a company that knew it needed outside innovation. Microsoft proves mass does not have to mean slow if leadership actively fights entropy.',
    keyNumbers: [
      'Azure revenue: $100B+ run rate',
      'Office 365 subscribers: 400M+',
      'GitHub developers: 100M+',
      'OpenAI investment: $13B',
      'Copilot revenue: $10B+ run rate',
      'Gaming revenue: $25B+ (with Activision)',
    ],
    enablers: [
      'Azure growth engine',
      'OpenAI partnership',
      'Enterprise relationships',
      'Nadella leadership',
      'Copilot AI integration',
    ],
    friction: [
      '228K employees to align',
      'Cloud competition (AWS, Google)',
      'Antitrust (Activision scrutiny)',
      'OpenAI governance drama',
      'Legacy product maintenance',
    ],
    quotable: 'Nadella took a calcifying giant and made it move again. Not by shrinking but by changing the culture. Microsoft proves mass does not have to mean slow if leadership actively fights entropy.',
  },

  'alphabet': {
    slug: 'alphabet',
    name: 'Alphabet (Google)',
    analysisDate: '2026-01-18',
    gpiScore: 4.55,
    state: 'Transitioning',
    ticker: 'GOOGL',
    marketCap: '~$2T',
    employees: 180000,
    revenue: '$350B (FY2025)',
    founded: 1998,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Consensus culture slows decisions. AI competition forced faster movement. Gemini launched under pressure.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Killed Google+ (eventually). Stadia dead. But many products linger. Gemini image issues fixed fast.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Research talent strong. But AI researchers leaving for startups. Knowledge walks out door.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: 'Search ads fund everything. YouTube locked in. Cloud growing but not dominant.' },
      { dimension: 'Talent Flow', score: 5, explanation: 'AI talent war with OpenAI, Anthropic (founders left Google). Still attracts but retention harder.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'AI infrastructure massive. YouTube content costs. But ads fund everything.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Research published but productization slow. "Transformer" invented here, OpenAI commercialized it.' },
    ],
    pattern: 'The AI-Awakened Giant',
    patternDescription: 'Google invented the transformer architecture that powers ChatGPT. Then watched OpenAI commercialize it. This is the research-to-product gap that consensus culture creates. The AI threat woke them up. Gemini and AI integration are the response. The question: can a company this size move fast enough when the threat is existential?',
    keyNumbers: [
      'Search market share: 90%+',
      'YouTube daily views: 1B+ hours',
      'Cloud revenue: $40B+ annually',
      'AI researchers: 4,000+',
      'Transformer paper citations: 100,000+',
      'Antitrust fines (EU): $10B+ total',
    ],
    enablers: [
      'Search ads cash machine',
      'AI research depth',
      'YouTube moat',
      'Cloud growth',
      'Android ecosystem',
    ],
    friction: [
      'OpenAI/Microsoft threat',
      'Consensus culture',
      'Antitrust pressure',
      'AI talent departures',
      'Product graveyard reputation',
    ],
    quotable: 'Google invented the transformer architecture that powers ChatGPT. Then watched OpenAI commercialize it. This is the research-to-product gap that consensus culture creates.',
  },

  'byd': {
    slug: 'byd',
    name: 'BYD',
    analysisDate: '2026-01-13',
    gpiScore: 3.4,
    state: 'Field',
    marketCap: '~$124B',
    employees: 968900,
    revenue: '$117.84B TTM',
    founded: 1995,
    dimensions: [
      { dimension: 'Decision Latency', score: 3, explanation: 'Cell-phone-speed product updates. 21 models upgraded simultaneously. Factories on 4 continents ramping in parallel.' },
      { dimension: 'Error Correction', score: 3, explanation: 'Pivoted to hybrids when pure EV slowed. Hit 1M overseas when China saturated. 538 patents = rapid iteration.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Vertical integration keeps knowledge internal but distributed. 120K engineers across divisions.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Modular systems, not rigid integration. Blade Battery works across lines. Factories can switch models.' },
      { dimension: 'Talent Flow', score: 3, explanation: '968,900 employees, aggressive hiring. Some overseas culture friction but core China operations flow well.' },
      { dimension: 'Capital Intensity', score: 4, explanation: 'Labor-intensive over automation. More flexible than Tesla approach. 18% battery cost reduction.' },
      { dimension: 'Knowledge Velocity', score: 3, explanation: 'Multiple launches per year. Megawatt charging developed fast. Blade 2.0 at CES 2026.' },
    ],
    pattern: 'Vertical Integration for Speed, Not Control',
    patternDescription: 'BYD inverted the traditional logic. Most companies integrate for cost and control, which creates rigidity. BYD built integration for speed and flexibility. Every component is modular. Every factory is retoolable. Result: 1 million employees moving like a startup. Same strategy as Tesla. Opposite architecture. Opposite outcomes.',
    keyNumbers: [
      '4.6M vehicles sold 2025 (2.26M BEVs)',
      '12.1% global BEV market share (vs Tesla 8.8%)',
      '1.05M overseas sales (up 150%)',
      '538 new patents in 2025',
      '120,000 engineers',
      'Forward P/E: 23x (vs Tesla 400x)',
    ],
    enablers: [
      '75% vertical integration for cost and speed',
      'Blade Battery 2.0 bridging LFP safety and NMC density',
      'Megawatt fast-charging (1,000kW)',
      'Global factory network: Thailand, Hungary, Turkey, Brazil',
      '$26.65B cumulative R&D investment',
    ],
    friction: [
      'China domestic market saturation',
      'Overseas management culture challenges (Glassdoor 3.0/5)',
      'EU/US tariff barriers and political risk',
      '2026 profitability pressure from price wars',
    ],
    quotable: 'BYD dethroned Tesla not by being cheaper or Chinese. By being faster. Architecture matters more than strategy.',
  },

  'costco': {
    slug: 'costco',
    name: 'Costco',
    analysisDate: '2026-01-18',
    gpiScore: 3.85,
    state: 'Transitioning (lower)',
    ticker: 'COST',
    marketCap: '~$419B',
    employees: 341000,
    revenue: '$280.39B TTM',
    founded: 1983,
    dimensions: [
      { dimension: 'Decision Latency', score: 4, explanation: 'Matrix structure with centralized strategy but regional autonomy. CEO engages directly with frontline.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Core model works, so no dramatic pivots needed. AI demand forecasting saved $100M in bakery waste.' },
      { dimension: 'Knowledge Location', score: 3, explanation: '76% managers promoted from within. 6% turnover compounds knowledge. 98%+ in-stock levels.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: '876+ warehouses is significant footprint, but model is simple and replicable. Kirkland gives supply chain control.' },
      { dimension: 'Talent Flow', score: 3, explanation: 'Superpower: 6-8% turnover vs 60% industry. 94% retention after year one. 76% managers started hourly.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'Massive physical footprint (150K sq ft warehouses). But $822K revenue/employee shows efficiency.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'AI provides real-time inventory signals. Digital wallet increased checkout speeds 20%.' },
    ],
    pattern: 'The Sufficiency Model at Scale',
    patternDescription: 'Costco demonstrates that not every company needs constant transformation. When your model works, when employees stay, when customers return, when margins are healthy, the goal is not disruption but disciplined execution. This is the anti-transformation case study, proving that cultural infrastructure can be more durable than technological infrastructure.',
    keyNumbers: [
      '876+ warehouses globally',
      '6% employee turnover (vs 60% industry)',
      '76% managers promoted from within',
      '60%+ domestic warehouse club market share',
      '$822K revenue per employee',
      'Glassdoor: 3.9/5.0, 72% recommend',
    ],
    enablers: [
      'Industry-leading employee retention',
      '76% internal promotion preserves culture',
      'AI demand forecasting saves $100M+',
      'Simple, replicable model',
      'Kirkland private label control',
      'Membership model creates loyalty',
    ],
    friction: [
      'Centralized strategic decision-making',
      '876+ warehouse footprint creates capital intensity',
      'Matrix structure adds layers',
      'Physical retail limits full digital pivot',
    ],
    quotable: 'When your turnover is 6% in an industry averaging 60%, you are not stuck in the past. You have found something others cannot replicate.',
  },

  'intel': {
    slug: 'intel',
    name: 'Intel',
    analysisDate: '2026-01-20',
    gpiScore: 7.0,
    state: 'Particle',
    ticker: 'INTC',
    marketCap: '~$242B',
    employees: 88400,
    revenue: '$53.43B TTM',
    founded: 1968,
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: 'CEO forced out Dec 2024, interim co-CEO structure creates friction, years late to AI wave.' },
      { dimension: 'Error Correction', score: 7, explanation: '35,500 layoffs as primary adaptation instead of strategic pivots. Failed to kill underperforming bets early.' },
      { dimension: 'Knowledge Location', score: 6, explanation: 'Engineering expertise siloed from market decisions. NVIDIA partnership needed for AI knowledge.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: 'Massive fab infrastructure ($10-20B per fab), cannot pivot to fabless model.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'No raises for 1.5 years, benefits cut, survivor anxiety from 32% headcount reduction.' },
      { dimension: 'Capital Intensity', score: 9, explanation: 'Semiconductor fabs among most capital-intensive businesses. $10-20B per fab.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: 'Engineering can ship, but strategic knowledge filtered. Interim structure adds handoffs.' },
    ],
    pattern: 'Mass as Destiny',
    patternDescription: 'Intel spent decades accumulating organizational and capital mass that once ensured dominance but now ensures inertia. The company cannot abandon its fabs, cannot match NVIDIA AI ecosystem, and cannot stop cutting people. Even if Intel builds the best chip, it arrives years after the market already chose NVIDIA for AI and TSMC for manufacturing.',
    keyNumbers: [
      '35,500 layoffs in less than 2 years',
      '$5B NVIDIA partnership',
      '18A process ahead of TSMC 2nm',
      'Forward P/E: 108.68 (priced for perfection)',
      'No raises for 1.5 years',
      'Interim co-CEO structure',
    ],
    enablers: [
      '18A Process lead over TSMC',
      'NVIDIA Partnership creates AI access',
      'Core Ultra Series 3 competitive',
      'US Manufacturing government support',
      'Stock momentum (130% gain)',
    ],
    friction: [
      'Layoffs as primary adaptation',
      'CEO forced out, interim structure',
      'No raises for 1.5 years',
      'Massive capital lock-in ($10-20B per fab)',
      'Missed mobile, GPUs, AI markets',
      'Benefits clawed back',
    ],
    quotable: 'Intel sits at 7.0, the exact threshold where organizations cross from transitioning to particle. The direction of travel is clear.',
  },

  'ups': {
    slug: 'ups',
    name: 'UPS',
    analysisDate: '2026-01-16',
    gpiScore: 6.8,
    state: 'Transitioning (upper)',
    ticker: 'UPS',
    marketCap: '~$92B',
    employees: 490000,
    revenue: '$89.5B TTM',
    founded: 1907,
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: '28 committees previously involved in funding decisions. Functional structure with centralized control.' },
      { dimension: 'Error Correction', score: 6, explanation: 'Amazon dependency persisted for years before aggressive correction. Layoffs as primary adaptation.' },
      { dimension: 'Knowledge Location', score: 6, explanation: 'Heavy AI investment (ORION, digital twins). But 119 years of institutional knowledge lives in people.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: '$9B automation commitment. 490,000 employees with 5-year union contract. Massive physical infrastructure.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'Strong promote-from-within culture. But union seniority rewards tenure over skill.' },
      { dimension: 'Capital Intensity', score: 9, explanation: 'Extremely capital-intensive: physical logistics network, $9B automation, union wage commitments.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: 'ORION provides real-time route optimization. But scale creates lag.' },
    ],
    pattern: 'Layoffs as Transformation',
    patternDescription: 'UPS is attempting transformation through subtraction rather than metabolic change. Cut 48,000 jobs. Close 200 facilities. Reduce Amazon volume by 50%. The assumption: shrink the particle mass and what remains will be nimbler. The problem: the underlying metabolism has not changed. They are making a smaller particle, not a field.',
    keyNumbers: [
      '48,000+ jobs cut in 2025',
      '200 facilities closing by 2028',
      '$9B automation investment',
      '340,000 Teamsters members',
      '50%+ Amazon volume reduction',
      'Market cap down 14% YoY',
    ],
    enablers: [
      'Carol Tomé as first external CEO',
      '"Better not bigger" strategy',
      '$9B automation modernizes operations',
      'ORION and AI tools',
      'Reducing Amazon dependency',
    ],
    friction: [
      '5-year Teamsters contract through 2028',
      '119 years of institutional culture',
      'Physical infrastructure path dependency',
      'Functional org structure maintains silos',
      'Layoffs creating knowledge loss',
    ],
    quotable: 'UPS is cutting 48,000 jobs but not changing how decisions get made. They are shrinking the particle, not transforming it.',
  },

  'fedex': {
    slug: 'fedex',
    name: 'FedEx',
    analysisDate: '2026-01-18',
    gpiScore: 5.8,
    state: 'Transitioning',
    ticker: 'FDX',
    marketCap: '~$73.9B',
    employees: 500000,
    revenue: '$88.6B TTM',
    founded: 1971,
    dimensions: [
      { dimension: 'Decision Latency', score: 6, explanation: 'Only 2nd CEO ever, 500K employees, multi-year transformation timelines.' },
      { dimension: 'Error Correction', score: 5, explanation: 'Network 2.0 closing 30% facilities, but layoffs as primary mechanism.' },
      { dimension: 'Knowledge Location', score: 5, explanation: '2 petabytes data, digital twin, but "miscommunication" in Glassdoor.' },
      { dimension: 'Structural Lock-In', score: 7, explanation: 'Decades of Express/Ground separation, massive physical infrastructure.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'CEO rose internally, 57% recommend, but "too many managers."' },
      { dimension: 'Capital Intensity', score: 7, explanation: 'Double UPS aircraft, extensive warehouses, actively rightsizing.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: '100B transactions, real-time tracking, but org hierarchy slows flow.' },
    ],
    pattern: 'Transformation Through Separation',
    patternDescription: 'FedEx is becoming more unified by splitting apart. The Freight spin-off removes a business model mismatch, while Network 2.0 finally integrates Express and Ground. The parallel separation-and-integration approach is a bet that you can lower GPI by removing what does not belong while unifying what should have been together all along.',
    keyNumbers: [
      'Freight spin-off: June 1, 2026',
      'Network 2.0: closing 30% distribution centers',
      'DRIVE program: $4B cost reductions by FY2027',
      '40%+ sortation automated',
      '100B+ transactions/year',
      'Only 2nd CEO in history',
    ],
    enablers: [
      'Network 2.0 integrating Express and Ground',
      'DRIVE program on track for $4B savings',
      '40%+ sortation automation',
      'Freight spin-off removing mismatch',
      'Stock outperforming UPS',
    ],
    friction: [
      'Layoffs as primary error correction',
      'Decades of Express/Ground cultural silos',
      'Massive physical infrastructure',
      '"Too many managers" in reviews',
      'Founder culture persists',
    ],
    quotable: 'FedEx at 5.8 sits exactly 1.0 point below UPS at 6.8, and the gap explains the stock performance difference.',
  },

  'target': {
    slug: 'target',
    name: 'Target',
    analysisDate: '2026-01-18',
    gpiScore: 5.3,
    state: 'Transitioning',
    ticker: 'TGT',
    marketCap: '~$50B',
    employees: 440000,
    revenue: '$105.24B TTM',
    founded: 1902,
    dimensions: [
      { dimension: 'Decision Latency', score: 6, explanation: 'Too many layers and overlapping work slowed decisions per CEO diagnosis. Managers cut 3x harder than ICs.' },
      { dimension: 'Error Correction', score: 5, explanation: 'Using layoffs as blunt error correction. 18 months of paralysis before action.' },
      { dimension: 'Knowledge Location', score: 5, explanation: 'Store Companion GenAI and ChatGPT Enterprise pushing knowledge out, but corporate silos persist.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: '2,000 stores create rigidity, but stores-as-hubs strategy provides omnichannel flexibility.' },
      { dimension: 'Talent Flow', score: 5, explanation: 'Fiddelke 22-year intern-to-CEO shows mobility possible. Glassdoor 3.4/5 shows favoritism complaints.' },
      { dimension: 'Capital Intensity', score: 6, explanation: '$5B annual capex, 2,000 stores, stock down 50%+ from all-time high.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: 'AI investments accelerating flow, but 18 months struggling with obvious problems.' },
    ],
    pattern: 'Cutting Through the Cheap Chic',
    patternDescription: 'Target represents the mid-GPI retailer that built its brand on being faster and more stylish than Walmart, but allowed organizational complexity to erode that advantage. Growth creates complexity, complexity slows response, and eventually the only visible lever is headcount reduction.',
    keyNumbers: [
      '1,800 corporate roles cut (8% of HQ)',
      'Stock down 50%+ from 2021 high',
      '2,000 stores nationwide',
      'ChatGPT Enterprise to 18,000 employees',
      'Managers cut 3x harder than ICs',
      'CEO transition: Fiddelke taking over Feb 2026',
    ],
    enablers: [
      'Store Companion GenAI to all stores',
      'ChatGPT Enterprise (92% satisfaction)',
      'Stores-as-hubs omnichannel flexibility',
      'Fiddelke succession showing mobility',
      '$5B capital investment plan',
    ],
    friction: [
      '18 months of decision paralysis',
      'Too many layers and overlapping work',
      'Middle management bloat',
      'Stock down 50%+ from all-time high',
      'Using layoffs as primary correction',
    ],
    quotable: 'The complexity we have created over time has been holding us back. Too many layers and overlapping work have slowed decisions.',
  },

  'ford': {
    slug: 'ford',
    name: 'Ford',
    analysisDate: '2026-01-19',
    gpiScore: 5.9,
    state: 'Transitioning',
    ticker: 'F',
    marketCap: '~$55B',
    employees: 171000,
    revenue: '$189.6B TTM',
    founded: 1903,
    dimensions: [
      { dimension: 'Decision Latency', score: 6, explanation: 'Traditional hierarchy with 171K employees creates inertia, took years of EV losses to pivot.' },
      { dimension: 'Error Correction', score: 5, explanation: 'Lost $13B on EVs before course-correcting, layoffs as primary adaptation mechanism.' },
      { dimension: 'Knowledge Location', score: 5, explanation: 'New vehicle brain centralizing systems, but "who you know" culture persists.' },
      { dimension: 'Structural Lock-In', score: 7, explanation: '$19.5B pivot charge shows enormous switching costs, UAW contracts limit flexibility.' },
      { dimension: 'Talent Flow', score: 6, explanation: '8+ years to Supervisor, RTO mandate bungled, declining Glassdoor rating.' },
      { dimension: 'Capital Intensity', score: 8, explanation: 'Massive manufacturing footprint, $176B enterprise value, pivots cost billions.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: 'AI assistant and telematics improving flow, but years of EV losses before correction.' },
    ],
    pattern: 'Stranded Capacity',
    patternDescription: 'Ford built factories, hired workers, and invested billions for an EV future that did not arrive on schedule. Now the company has stranded capacity at facilities designed for high EV volumes, stranded talent in the form of laid-off workers, and stranded capital in the form of $19.5B in write-downs.',
    keyNumbers: [
      'Model e losses: $13B since 2023',
      '$19.5B special charges for pivot',
      'Hybrid sales up 22% YoY',
      'EV sales down 14% YoY',
      'F-Series: 828,832 units (best-selling truck)',
      '11,000 layoffs in 2025',
    ],
    enablers: [
      'Jim Farley decisive leadership',
      'New in-house vehicle brain architecture',
      'AI assistant to 8M customers',
      'Strong hybrid sales momentum',
      'F-Series cash flow stability',
    ],
    friction: [
      'Stranded EV capacity',
      'Multi-year layoff cycle (11,000+ more projected)',
      'UAW contracts constraining flexibility',
      'RTO mandate bungled',
      '"Who you know" culture persisting',
    ],
    quotable: 'Ford is correcting, but through headcount cuts rather than process changes. Even a 122-year-old company can move fast enough to bet on the future, but a capital-intensive manufacturer cannot pivot without massive financial pain.',
  },

  'blockbuster': {
    slug: 'blockbuster',
    name: 'Blockbuster',
    analysisDate: '2026-01-19',
    gpiScore: 8.55,
    state: 'Particle (Dead)',
    employees: 84300,
    revenue: '$6.1B (Peak 2004)',
    founded: 1985,
    dimensions: [
      { dimension: 'Decision Latency', score: 9, explanation: '6 years to respond to Netflix. Rejected $50M acquisition in 2000. Board politics killed online pivot in 2007.' },
      { dimension: 'Error Correction', score: 9, explanation: 'Unprofitable since 1997. Knew Netflix threat for decade. Shut down Total Access when it was winning.' },
      { dimension: 'Knowledge Location', score: 8, explanation: '9,000 stores, zero field intelligence reaching HQ. CEO laughed at Netflix offer.' },
      { dimension: 'Structural Lock-In', score: 9, explanation: 'Physical stores with leases. $900M debt. Late fees as revenue model could not be eliminated.' },
      { dimension: 'Talent Flow', score: 7, explanation: 'Antioco trying to adapt, Icahn ousted him. Keyes doubled down on brick-and-mortar.' },
      { dimension: 'Capital Intensity', score: 9, explanation: 'Massive physical infrastructure. Netflix digital, Blockbuster locked in atoms.' },
      { dimension: 'Knowledge Velocity', score: 8, explanation: 'Management did not understand streaming. 6 years behind market.' },
    ],
    pattern: 'The Textbook GPI Death',
    patternDescription: 'Blockbuster is the textbook GPI death. Success creates rigidity: 9,000 stores became 9,000 anchors. Late fees were margin: 16% of revenue from customer friction. Board politics killed adaptation: Antioco was right, got fired anyway. Debt accelerated death: $900M made pivoting impossible.',
    keyNumbers: [
      'Peak stores: 9,094 (2004)',
      'Late fees: $800M (16% of revenue)',
      'Rejected $50M Netflix offer (2000)',
      'Sold to Dish for $320M (2011)',
      'Debt at spinoff: $905M',
      'Time to respond to Netflix: 6 years',
    ],
    enablers: [
      'None remaining',
    ],
    friction: [
      '6 years to respond to Netflix',
      '$50M acquisition rejection',
      'Board politics (Icahn ousting Antioco)',
      '$900M debt load',
      '9,000 physical stores with leases',
      'Late fees as revenue dependency',
    ],
    quotable: 'Blockbuster GPI crossed 7.0 around 2004. They were dead. They just did not know it yet. The financials said healthy. The GPI said hospice.',
  },

  'comcast': {
    slug: 'comcast',
    name: 'Comcast',
    analysisDate: '2026-01-16',
    gpiScore: 6.95,
    state: 'Transitioning (upper)',
    ticker: 'CMCSA',
    marketCap: '~$172B',
    employees: 182000,
    revenue: '$124B',
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: 'Family control creates structural bottleneck, 894 executives.' },
      { dimension: 'Error Correction', score: 6, explanation: 'Versant spinoff shows adaptation, but took years.' },
      { dimension: 'Knowledge Location', score: 6, explanation: 'Siloed business units, internal confusion.' },
      { dimension: 'Structural Lock-In', score: 9, explanation: 'Massive cable infrastructure, theme parks, studios.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'Boys club culture, wage compression, offshoring.' },
      { dimension: 'Capital Intensity', score: 9, explanation: 'Infrastructure-heavy, continuous capital demands.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: 'Legacy systems, fragmented analytics.' },
    ],
    pattern: 'Controlled Decay',
    patternDescription: 'Comcast is managing decline rather than driving transformation. The Versant spinoff is not innovation. It is amputation: cutting off the gangrenous limb (declining cable networks) to save the body (broadband + streaming). This is a valid survival strategy but it is not transformation.',
    keyNumbers: [
      '894 executives',
      'Brian Roberts: 33% voting control, CEO since 2002',
      'Four years of layoffs',
      '182,000 employees across silos',
      'Versant spinoff removing cable networks',
    ],
    enablers: [
      'Versant spinoff shedding calcified assets',
      'Peacock streaming platform',
      'Broadband infrastructure valuable',
      'Universal Studios content library',
      'Strong cash flow',
    ],
    friction: [
      'Family control creates bottleneck',
      '182,000 employees across silos',
      'Legacy cable demands continuous capital',
      'Four years of layoffs damage knowledge',
      'Boys club culture limits mobility',
    ],
    quotable: 'When one person controls 33% of voting power, the organization metabolism is bounded by that person decision speed and risk tolerance.',
  },

  'progressive': {
    slug: 'progressive',
    name: 'Progressive',
    analysisDate: '2026-01-19',
    gpiScore: 3.85,
    state: 'Transitioning (lower)',
    ticker: 'PGR',
    marketCap: '~$127B',
    employees: 66308,
    revenue: '$85.2B TTM',
    founded: 1937,
    dimensions: [
      { dimension: 'Decision Latency', score: 4, explanation: 'CEO rose from claims rep to CEO; 3-year strategic cycles; 80 executives suggest some layers.' },
      { dimension: 'Error Correction', score: 4, explanation: 'AI delivers 15% faster claims, 9% better pricing; but uses layoffs as adaptation.' },
      { dimension: 'Knowledge Location', score: 3, explanation: '14B+ miles of data in ML systems; 6+ bots democratize access; data flows through systems not fiefdoms.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Three clear segments allow focused adaptation; digital-first approach; but 66K employees create structural weight.' },
      { dimension: 'Talent Flow', score: 5, explanation: 'CEO story is powerful but Glassdoor cites limited advancement paths; external hires favored for business roles.' },
      { dimension: 'Capital Intensity', score: 3, explanation: 'Asset-light insurance model; no factories; $2.2B ICT spend is digital-focused and scalable.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Real-time Snapshot data; AI photo damage assessment; but 3-year planning cycles slow some flow.' },
    ],
    pattern: 'Data as Moat',
    patternDescription: 'Progressive turned a commodity business into a technology play by betting early on telematics. While competitors priced risk using demographic tables, Progressive built a 14-billion-mile dataset that continuously improves its pricing accuracy. The company proves that even in a legacy industry, whoever owns the data owns the market.',
    keyNumbers: [
      'Snapshot: 14B+ miles collected',
      '9% more accurate risk pricing',
      '15% faster claims with AI',
      '#2 U.S. auto insurer',
      '$2.2B annual ICT spending',
      'Glassdoor: 3.9/5.0, 75% recommend',
    ],
    enablers: [
      'Snapshot telematics: 14B+ miles',
      '9% pricing accuracy advantage',
      'AI-powered claims (15% faster)',
      'CEO with 36-year tenure',
      '$2.2B annual ICT investment',
    ],
    friction: [
      'Processing outsourcing to India',
      'Micromanagement culture',
      'Limited career advancement paths',
      'External hires favored',
      '20% of Snapshot users see rate increases',
    ],
    quotable: 'Progressive proves you can be a legacy insurer and still move like a tech company, with 14 billion miles of telematics data powering real-time risk assessment.',
  },

  'salesforce': {
    slug: 'salesforce',
    name: 'Salesforce',
    analysisDate: '2026-01-20',
    gpiScore: 4.35,
    state: 'Transitioning',
    ticker: 'CRM',
    marketCap: '~$224B',
    employees: 72682,
    revenue: '$40.31B TTM',
    founded: 1999,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Quarterly product releases show cadence but 72,682 employees create layers. CEO deeply involved indicates centralized authority.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Fast pivot to Agentforce ($540M ARR, 330% growth) shows adaptation. However, 5,000 layoffs and $330M restructuring.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Agentforce encoding 3.2 trillion tokens shows distributed knowledge systems. But Glassdoor mentions siloed divisions.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: 'SaaS model allows product pivots, but 72,682 employees across multiple clouds create complexity.' },
      { dimension: 'Talent Flow', score: 5, explanation: 'Internal mobility possible when mandated (4,000 support to sales). Glassdoor concerns about promotion transparency.' },
      { dimension: 'Capital Intensity', score: 3, explanation: 'Pure SaaS, asset-light. $40.3B revenue without physical assets. Can pivot without stranded capital.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'AI dashboards and quarterly releases show regular but not real-time information flow.' },
    ],
    pattern: 'AI as Operating System Upgrade',
    patternDescription: 'Salesforce is betting that AI agents can reduce organizational friction faster than traditional restructuring. Instead of removing layers, the company is automating through them. The question is whether you can code your way around calcification without addressing the organizational mass creating it.',
    keyNumbers: [
      'Agentforce: 3.2 trillion tokens processed',
      'Agentforce ARR: $540M (330% growth)',
      '21.7% global CRM market share',
      '150,000+ customers',
      '5,000 layoffs in 2025',
      '$330M restructuring budget',
    ],
    enablers: [
      'Agentforce platform (3.2T tokens, $540M ARR)',
      'SaaS architecture enabling rapid pivots',
      'Workforce rebalancing capability',
      '21.7% CRM market share',
      'Strong employer brand (4.1/5 Glassdoor)',
    ],
    friction: [
      '72,682 employees creating latency',
      'Layoffs as primary adaptation',
      'Glassdoor: bureaucracy, constant pivoting',
      'Product division silos',
      'Centralized decision authority',
    ],
    quotable: 'Salesforce is trying to become fluid by teaching software to navigate particle behavior. You cannot automate around approval chains if those chains still control budget and strategy.',
  },

  'home-depot': {
    slug: 'home-depot',
    name: 'Home Depot',
    analysisDate: '2026-01-18',
    gpiScore: 4.65,
    state: 'Transitioning',
    ticker: 'HD',
    marketCap: '~$378B',
    employees: 470100,
    revenue: '$166.18B TTM',
    founded: 1978,
    dimensions: [
      { dimension: 'Decision Latency', score: 5, explanation: 'Bold strategic moves ($18.25B SRS acquisition, Google AI partnership) but scale creates implementation lag.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Pivoting from DIY to pro market, actively restructuring supply chain, closing underperforming DCs.' },
      { dimension: 'Knowledge Location', score: 4, explanation: 'Heavy AI investment (Magic Apron, Gemini Enterprise, Rilla coaching) but channel silos persist.' },
      { dimension: 'Structural Lock-In', score: 5, explanation: '4,300+ physical locations but using M&A (SRS, GMS) to add modular capabilities.' },
      { dimension: 'Talent Flow', score: 5, explanation: 'CEO promoted from within (20 years), good Glassdoor scores, but frontline stress on hours.' },
      { dimension: 'Capital Intensity', score: 6, explanation: 'Highly capital intensive but deploying aggressively on transformation.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Real-time AI coaching scaling nationally, but retail cycles create natural limits.' },
    ],
    pattern: 'Scale as Transformation Platform',
    patternDescription: 'Home Depot demonstrates that massive scale can be leveraged for transformation rather than being a barrier to it. Where most retailers calcify, Home Depot uses scale to make bold bets: the largest acquisition in company history, first-mover AI deployments, and aggressive supply chain restructuring.',
    keyNumbers: [
      'SRS acquisition: $18.25B',
      '4,300+ locations (stores + SRS)',
      'Pro business: 50% of revenue',
      'TAM expanded $50B via SRS',
      'Glassdoor: 3.8/5.0, 71% recommend',
      'Stock down 11% YTD 2025 (housing headwinds)',
    ],
    enablers: [
      'Google Cloud AI partnership (Gemini Enterprise)',
      'Magic Apron AI scaling nationally',
      'SRS acquisition expanding pro reach',
      'CEO Ted Decker with 20 years context',
      'Pro business at 50% diversifies from DIY',
    ],
    friction: [
      'Housing market headwinds',
      '4,300+ physical locations create inertia',
      'Public market pressure during downturn',
      'Integration complexity from acquisitions',
      'Frontline workforce stress',
    ],
    quotable: 'Scale does not have to mean calcification. Home Depot is proving that culture and strategy matter more than size.',
  },

  'gm': {
    slug: 'gm',
    name: 'General Motors',
    analysisDate: '2026-01-19',
    gpiScore: 5.9,
    state: 'Transitioning',
    ticker: 'GM',
    marketCap: '~$76B',
    employees: 162000,
    revenue: '$187.4B',
    founded: 1908,
    dimensions: [
      { dimension: 'Decision Latency', score: 6, explanation: 'Glassdoor cites "approval from multiple teams for small changes," but Barra consolidated leadership enables strategic pivots.' },
      { dimension: 'Error Correction', score: 5, explanation: 'Taking $7.6B in EV write-downs shows adaptation, but relies on layoffs rather than process change.' },
      { dimension: 'Knowledge Location', score: 5, explanation: 'Building "data factory" with NVIDIA digital twins, but four brand divisions create natural silos.' },
      { dimension: 'Structural Lock-In', score: 7, explanation: '116-year legacy, billions in factory infrastructure, $7.6B write-down shows cost of direction change.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'UAW structure limits flexibility, Glassdoor shows "declining trust in leadership."' },
      { dimension: 'Capital Intensity', score: 8, explanation: 'Manufacturing requires massive physical assets, every pivot costs billions.' },
      { dimension: 'Knowledge Velocity', score: 5, explanation: 'Ultifi platform enables OTA updates, but "lack of transparency" persists per Glassdoor.' },
    ],
    pattern: 'The Detroit Paradox',
    patternDescription: 'GM is simultaneously too big to pivot quickly and too profitable to fail slowly. Record profits ($14.9B), record stock (+55%), and U.S. sales leadership mean no burning platform forces transformation. Yet $7.6B in EV write-downs reveals the cost of moving slower than the market.',
    keyNumbers: [
      'EV write-downs: $7.6B in 2025',
      'EV sales: 169,887 units (+48% YoY)',
      'ICT spending: $10.9B annually',
      'Stock: +55% in 2025',
      '2024 profit: $14.9B (record)',
      '116 years old',
    ],
    enablers: [
      'Mary Barra leadership continuity',
      '$10.9B annual ICT spending',
      'Ultifi software platform',
      'Google Gemini integration (2026)',
      'Record profitability provides capital',
    ],
    friction: [
      '116-year legacy creating lock-in',
      '162,000 employees and four divisions',
      'UAW union structure limiting flexibility',
      'Capital intensity: every pivot costs billions',
      'Reliance on layoffs as adaptation',
    ],
    quotable: 'The Detroit Paradox: too big to pivot quickly, too profitable to fail slowly.',
  },

  'ibm': {
    slug: 'ibm',
    name: 'IBM',
    analysisDate: '2026-01-20',
    gpiScore: 6.35,
    state: 'Transitioning (upper)',
    ticker: 'IBM',
    marketCap: '~$285B',
    employees: 270300,
    revenue: '$65.4B TTM',
    founded: 1911,
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: 'Layoffs in small chunks to avoid WARN act, multiple management layers across 270K+ employees.' },
      { dimension: 'Error Correction', score: 6, explanation: 'Using layoffs as primary adaptation (9,000 cuts), but AI business doubled.' },
      { dimension: 'Knowledge Location', score: 6, explanation: 'Siloed divisions visible in names (SoftLayer, Neudesic, Cloud Classic vs new Cloud).' },
      { dimension: 'Structural Lock-In', score: 7, explanation: '115 years old, still integrating $34B Red Hat, cannot sunset Cloud Classic cleanly.' },
      { dimension: 'Talent Flow', score: 7, explanation: '25% cut rate in Cloud Classic, forever layoffs pattern, relocation disguised as policy.' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'Mixed model: software/consulting (asset-light) vs infrastructure (asset-heavy). $15B+ FCF.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: '270K employees and siloed divisions slow info flow, org changes via manager invites.' },
    ],
    pattern: 'Buying Speed You Cannot Build',
    patternDescription: 'IBM is trying to purchase transformation velocity through acquisitions ($34B Red Hat, $11B Confluent) and AI platforms rather than reducing the organizational mass that slows everything down. The pattern repeats: buy the new thing, run it in parallel with the old thing, cut the old thing headcount slowly, declare progress.',
    keyNumbers: [
      'AI business: $9.5B (doubled from $5B)',
      'Red Hat acquisition: $34B',
      'Confluent acquisition: $11B (mid-2026)',
      '9,000 layoffs announced',
      '115 years old',
      'Market cap +40.57% in one year',
    ],
    enablers: [
      'AI business doubled from $5B to $9.5B',
      'Watsonx AI platform gaining traction',
      '$11B Confluent acquisition',
      '$15B+ free cash flow',
      'Arvind Krishna focus on cloud/AI',
    ],
    friction: [
      'Forever layoffs: 9,000 cuts avoiding WARN act',
      'Cloud Classic vs new Cloud structure',
      'Siloed divisions creating barriers',
      '$34B Red Hat integration still ongoing',
      '115 years of technical debt',
    ],
    quotable: 'You can buy agility but you cannot build it when you are carrying 115 years of mass.',
  },

  'oracle': {
    slug: 'oracle',
    name: 'Oracle',
    analysisDate: '2026-01-20',
    gpiScore: 6.4,
    state: 'Transitioning (upper)',
    ticker: 'ORCL',
    marketCap: '~$549B',
    employees: 162000,
    revenue: '$61.01B TTM',
    founded: 1977,
    dimensions: [
      { dimension: 'Decision Latency', score: 6, explanation: 'Co-CEO structure adds coordination overhead. Restructuring only 50% spent after six months.' },
      { dimension: 'Error Correction', score: 7, explanation: 'Layoffs as primary adaptation (10,000-20,000 cuts). Three waves instead of strategic pivots.' },
      { dimension: 'Knowledge Location', score: 5, explanation: '600+ AI agents suggest distributed knowledge. But 162,000 employees with acquisition debt create silos.' },
      { dimension: 'Structural Lock-In', score: 7, explanation: '$50B capex commits to infrastructure path. Cannot exit legacy on-premises.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'Layoffs via Zoom destroy trust. Command-and-control limits mobility. 68% recommendation rate.' },
      { dimension: 'Capital Intensity', score: 8, explanation: '$50B projected capex is extreme. $500B joint venture with OpenAI/SoftBank.' },
      { dimension: 'Knowledge Velocity', score: 6, explanation: 'Fast in product (817% multicloud growth). Slow in org (restructuring execution).' },
    ],
    pattern: 'Infrastructure Arms Race',
    patternDescription: 'Oracle is betting its future on a capital-intensive infrastructure buildout to compete with hyperscalers, precisely when organizational mass makes strategic pivots nearly impossible. The company that built its empire on flexible database software is now locked into a $50B annual capex commitment.',
    keyNumbers: [
      'Capex: $50B projected for FY2026',
      'Layoffs: 10,000-20,000 in 2026',
      'OpenAI partnership: $500B joint venture',
      'IaaS growth: 68%',
      'Multicloud database: +817% YoY',
      'Cloud revenue: $8B (up 34%)',
    ],
    enablers: [
      '600+ AI agents deployed',
      '$300B OpenAI commitment',
      'IaaS growth at 68%',
      'Database 26ai innovation',
      '$523B performance obligations',
    ],
    friction: [
      'Layoffs as primary adaptation (10K-20K cuts)',
      '$50B capex locks into infrastructure path',
      'Command-and-control culture',
      'Cannot exit legacy on-premises',
      'Acquisition integration debt',
    ],
    quotable: 'Oracle is spending $50 billion on infrastructure while laying off 20,000 people. That is not transformation. That is trading one rigidity for another.',
  },

  'att': {
    slug: 'att',
    name: 'AT&T',
    analysisDate: '2026-01-16',
    gpiScore: 7.55,
    state: 'Particle',
    ticker: 'T',
    marketCap: '~$170B',
    employees: 141000,
    revenue: '~$122B',
    founded: 1983,
    dimensions: [
      { dimension: 'Decision Latency', score: 8, explanation: '350-to-9 office consolidation, top-down RTO mandate, geographic chokepoints.' },
      { dimension: 'Error Correction', score: 7, explanation: 'Layoffs as primary mechanism, RTO backfired but pushed forward anyway.' },
      { dimension: 'Knowledge Location', score: 7, explanation: 'Siloed divisions, 45% workforce cuts taking institutional knowledge.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: 'Massive physical infrastructure, billions to reconfigure.' },
      { dimension: 'Talent Flow', score: 7, explanation: 'Layoffs dominant, RTO designed to trigger attrition.' },
      { dimension: 'Capital Intensity', score: 9, explanation: 'Telecom infrastructure, constant 5G/fiber capex required.' },
      { dimension: 'Knowledge Velocity', score: 7, explanation: '141K employees across divisions, RTO signals digital systems insufficient.' },
    ],
    pattern: 'Shrinking to Survive',
    patternDescription: 'AT&T transformation strategy is amputation: cut employees, cut offices, cut costs. The company has shed 45% of its workforce in five years while trying to maintain the same infrastructure footprint. This is not transformation, it is managed decline.',
    keyNumbers: [
      '115,000 employees cut (5 years)',
      'Office consolidation: 350 to 9',
      'Cost reduction target: $8B',
      'Wireless: 74M postpaid, 17M prepaid',
      'Fortune 500 rank dropped 5 spots',
      'Revenue per employee: $868K',
    ],
    enablers: [
      'Revenue per employee up 7%',
      '9-office consolidation reduces costs',
      '$8B cost reduction execution',
      'Wireless segment (70% revenue) stable',
      'Acquiring Lumen Quantum Fiber',
    ],
    friction: [
      '115,000 employees cut signals distress',
      'RTO mandate backfired (no desks, parking)',
      'Third place in wireless',
      'DirecTV sold at massive loss',
      'Layoffs as primary adaptation',
    ],
    quotable: 'AT&T cut 115,000 employees in five years. That is not transformation, that is amputation.',
  },

  'verizon': {
    slug: 'verizon',
    name: 'Verizon',
    analysisDate: '2026-01-16',
    gpiScore: 7.05,
    state: 'Particle',
    ticker: 'VZ',
    employees: 85000,
    dimensions: [
      { dimension: 'Decision Latency', score: 7, explanation: 'New CEO making fast cuts, reactive not proactive.' },
      { dimension: 'Error Correction', score: 7, explanation: 'Executing layoffs efficiently, core business eroding.' },
      { dimension: 'Knowledge Location', score: 7, explanation: 'Losing institutional knowledge with mass layoffs.' },
      { dimension: 'Structural Lock-In', score: 8, explanation: 'Heavy legacy infrastructure, union workforce.' },
      { dimension: 'Talent Flow', score: 6, explanation: 'Reacting to competition, not leading.' },
      { dimension: 'Capital Intensity', score: 7, explanation: 'Killing workforce without killing root costs.' },
      { dimension: 'Knowledge Velocity', score: 7, explanation: 'Calcified processes maintained while people cut.' },
    ],
    pattern: 'Managed Decline',
    patternDescription: 'Verizon is executing the "shrink to profitability" playbook: cut costs faster than revenue declines. This can work for a decade but it is not transformation. The $20M reskilling fund versus $1.8B in severance tells you where the real investment is going.',
    keyNumbers: [
      'Layoffs: 15,000 (15% of workforce)',
      'Severance charges: $1.8B (Q4 2025)',
      'Expected savings: $3-4B annually',
      '$20M reskilling vs $1.8B severance',
      'New CEO from PayPal',
    ],
    enablers: [
      'New leadership making hard decisions',
      'Fiber/5G infrastructure investments',
    ],
    friction: [
      'Mass layoffs destroy institutional knowledge',
      'T-Mobile continues market share gains',
      '"Age of AI" rhetoric without AI-native strategy',
      'Turnaround CEO pattern suggests more cuts',
    ],
    quotable: '$20M reskilling fund vs $1.8B severance = 1:90 ratio. That is not transformation, that is PR.',
  },

  'berkshire-hathaway': {
    slug: 'berkshire-hathaway',
    name: 'Berkshire Hathaway',
    analysisDate: '2026-01-19',
    gpiScore: 3.75,
    state: 'Transitioning (lower)',
    ticker: 'BRK.A',
    marketCap: '~$1.064T',
    employees: 392400,
    revenue: '$372B',
    founded: 1839,
    dimensions: [
      { dimension: 'Decision Latency', score: 3, explanation: '27-person HQ, "delegation just short of abdication," subsidiaries make all operational decisions autonomously.' },
      { dimension: 'Error Correction', score: 4, explanation: 'Subsidiaries self-correct (GEICO cut 7,700 jobs), but holding company slow to exit investment mistakes.' },
      { dimension: 'Knowledge Location', score: 3, explanation: 'Knowledge distributed to where it is needed, no bureaucratic filtering, each subsidiary is independent.' },
      { dimension: 'Structural Lock-In', score: 4, explanation: 'Conglomerate structure enables flexibility, but capital-intensive subsidiaries create constraints.' },
      { dimension: 'Talent Flow', score: 4, explanation: 'Long tenure rewarded (Abel groomed 25 years), no up-or-out, but Glassdoor notes "low opportunities."' },
      { dimension: 'Capital Intensity', score: 5, explanation: 'HQ is asset-light but subsidiaries mixed, insurance float is strategic advantage.' },
      { dimension: 'Knowledge Velocity', score: 4, explanation: 'Monthly reporting (not real-time), information flows when needed not continuously.' },
    ],
    pattern: 'The Anti-Bureaucracy Empire',
    patternDescription: 'Berkshire Hathaway is the largest proof of concept for minimal organizational friction. While other trillion-dollar companies employ thousands at headquarters, Berkshire runs on 27 people and monthly financial reports. Trust replaces oversight. Accountability replaces approval chains.',
    keyNumbers: [
      'HQ staff: 27 employees in Omaha',
      'Cash and T-bills: $350B+',
      'Insurance float: ~$176B',
      '90+ subsidiaries across 50+ industries',
      '19.9% compounded annual return (1964-2024)',
      'Glassdoor: 4.3/5.0, 77% recommend',
    ],
    enablers: [
      'Extreme decentralization eliminates friction',
      '$350B+ cash provides acquisition flexibility',
      '$176B insurance float as interest-free capital',
      '25-year succession planning',
      'Diversification across 90+ subsidiaries',
    ],
    friction: [
      'Post-Buffett uncertainty',
      'GEICO losing share to Progressive',
      'Finding "elephants" large enough at $1T+ scale',
      'Capital-intensive subsidiaries limit agility',
      'Leadership departures (Todd Combs to JPMorgan)',
    ],
    quotable: '27 people managing $1 trillion is either the purest expression of organizational fluidity or a governance risk hiding in plain sight.',
  },
};

export function getSnapshotBySlug(slug: string): CompanySnapshot | null {
  return snapshotsContent[slug.toLowerCase()] || null;
}

export function getSnapshotByName(name: string): CompanySnapshot | null {
  const slug = name.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  // Try direct match first
  if (snapshotsContent[slug]) return snapshotsContent[slug];

  // Try common variations
  const variations: Record<string, string> = {
    'warner-bros-discovery': 'wbd',
    'at-t': 'att',
    'procter-gamble': 'procter-gamble',
    'dicks-sporting-goods': 'dicks-sporting-goods',
  };

  if (variations[slug]) return snapshotsContent[variations[slug]] || null;

  // Search by name
  for (const snapshot of Object.values(snapshotsContent)) {
    if (snapshot.name.toLowerCase() === name.toLowerCase()) {
      return snapshot;
    }
  }

  return null;
}

export function getAllSnapshots(): CompanySnapshot[] {
  return Object.values(snapshotsContent);
}
